CREATE TABLE EXTEND_ACCESS 
("EXT_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
"EXT_USR_KEY" NUMBER NOT NULL ENABLE, 
"EXT_ACCESS_ID" NUMBER NOT NULL ENABLE, 
"EXT_INSTANCE_ID" NUMBER NOT NULL ENABLE, 
"EXT_INSTANCE_TYPE" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
"EXT_INSTANCE_NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
"EXT_ACCESS_END_DATE" DATE NOT NULL ENABLE, 
 CONSTRAINT "EXTEND_ACCESS_PK" PRIMARY KEY ("EXT_UUID")
);