apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: "oke-capoci"
  name: "oke-capoci"
  namespace: "default"
spec:
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
    kind: OCIManagedCluster
    name: "oke-capoci"
    namespace: "default"
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
    kind: OCIManagedControlPlane
    name: "oke-capoci"
    namespace: "default"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: OCIManagedCluster
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: "oke-capoci"
  name: "oke-capoci"
spec:
  compartmentId: "${OKE_COMPARTMENT_ID}"
  region: "${OKE_REGION}"
---
kind: OCIManagedControlPlane
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
metadata:
  name: "oke-capoci"
  namespace: "default"
spec:
  version: "v1.27.2"
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: "oke-capoci-mp-0"
  namespace: default
  annotations:
    "cluster.x-k8s.io/replicas-managed-by": ""
spec:
  clusterName: "oke-capoci"
  replicas: 1
  template:
    spec:
      clusterName: "oke-capoci"
      bootstrap:
        dataSecretName: ""
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        kind: OCIManagedMachinePool
        name: "oke-capoci-mp-0"
      version: "v1.27.2"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: OCIManagedMachinePool
metadata:
  name: "oke-capoci-mp-0"
  namespace: default
spec:
  version: "v1.27.2"
  nodeShape: "VM.Standard.E4.Flex"
  nodeSourceViaImage:
    imageId: ""   # specify in production
    bootVolumeSizeInGBs: 50
  nodeShapeConfig:
    ocpus: "1"