apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: example-config
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
    - clusters:
        selector:
          matchLabels:
            cluster: example    # Replace with in-cluster to deploy the example namespace
  template:
    metadata:
      labels:
        type: config
      name: 'example-config-{{ "{{" }}.name{{ "}}" }}'
    spec:
      project: {{ .Values.project }}
      sources:
        - repoURL: {{ .Values.repo }}
          targetRevision: HEAD
          path: apps/{{ "{{" }}.name{{ "}}" }}/example/_config_
          directory:
            recurse: true

      destination:
        server: '{{ "{{" }}.server{{ "}}" }}'
        namespace: example
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true