apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: cluster
    cluster: in-cluster
  name: in-cluster
  namespace: argocd
stringData:
  config: '{"bearerToken":"","tlsClientConfig":{"insecure":false,"caData":""}}'
  name: in-cluster
  server: https://kubernetes.default.svc
type: Opaque