# Kustomize application containing cluster configurations for the hub cluster.


apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hub-config
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
    - clusters:
        selector:
          matchLabels:
            type: "hub"

  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: 'hub-config'
    spec:
      project: default
      sources:
        # Global config for each cluster
        - repoURL: {{ .Values.repo }}
          targetRevision: HEAD
          path: apps/kustomize/config/env-type/{{ "{{" }}.metadata.labels.type{{ "}}" }}

      destination:
        server: '{{ "{{" }}.server{{ "}}" }}'
        namespace: argocd
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        automated:
          prune: true
          selfHeal: true