apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: reference-app-runtime
  namespace: reference-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: oci-vault
    kind: SecretStore
  target:
    name: reference-app-runtime
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: reference-app-runtime
