title: OKE RM - Base Network Infrastructure
description: Basic network infrastructure to start with OKE
informationalText: Basic network infrastructure
schemaVersion: 1.1.0
version: "20190304"
locale: "en"

variableGroups:

  - title: "Hidden"
    visible: false
    variables:
      - tenancy_ocid
      - compartment_ocid
      - region

  - title: "Network"
    variables:
      - network_compartment_id
      - create_vcn
      - vcn_id
      - vcn_name
      - vcn_cidr_block
      - vcn_dns_label
      - cni_type

  - title: "Control Plane"
    variables:
      - create_cp_subnet
      - cp_subnet_name
      - cp_connection_notice
      - cp_subnet_private
      - cp_allowed_source_cidr
      - cp_external_nat
      - allow_external_cp_traffic
      - cp_egress_cidr

  - title: "Worker"
    variables:
      - create_worker_subnet
      - worker_subnet_name
      - allow_worker_nat_egress

  - title: "Load Balancer"
    variables:
      - create_external_lb_subnet
      - external_lb_subnet_name
      - create_internal_lb_subnet
      - internal_lb_subnet_name

  - title: "Pod"
    variables:
      - create_pod_subnet
      - pod_subnet_name
      - allow_pod_nat_egress

  - title: "FSS"
    variables:
      - create_fss
      - fss_subnet_name

  - title: "Bastion"
    variables:
      - create_bastion_subnet
      - bastion_subnet_name
      - bastion_subnet_private

  - title: "Gateways"
    variables:
      - create_gateways
      - create_internet_gateway

  - title: "DRG"
    variables:
      - enable_drg
      - create_drg
      - drg_name
      - drg_id
      - create_drg_attachment
      - peer_vcns

  - title: "Additional Network"
    variables:
      - create_db_subnet
      - db_subnet_name
      - db_service_list
      - separate_db_nsg

variables:

  region:
    title: "Region"
    type: oci:identity:region:name
    required: true

  network_compartment_id:
    title: "Network Compartment"
    description: "All resources in this section will be created within the compartment chosen"
    type: oci:identity:compartment:id
    default: ${compartment_ocid}
    required: true

  cni_type:
    title: "CNI Type"
    description: "CNI to use for the OKE cluster"
    type: enum
    enum:
      - vcn_native
      - flannel
    required: true

# VCN

  create_vcn:
    title: "Create VCN"
    description: "If false, stack will create only the required NSGs"
    type: boolean

  vcn_id:
    title: "Existing VCN"
    type: oci:core:vcn:id
    dependsOn:
      compartmentId: ${network_compartment_id}
    required: true
    visible:
      not:
        - ${create_vcn}

  vcn_name:
    title: "VCN Name"
    description: "Name of the VCN to create"
    type: string
    required: true
    visible: ${create_vcn}

  vcn_cidr_block:
    title: "VCN CIDR block"
    description: "CIDR blocks to be allocated for the VCN. MUST BE A /16 VCN"
    type: string
    required: true
    pattern: "^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?).){2}0.0\/16$"
    visible: ${create_vcn}

  vcn_dns_label:
    title: "VCN DNS name"
    description: "DNS label fot the VCN. MUST BE UNIQUE across all the VCNs"
    type: string
    required: true
    pattern: "^[a-zA-Z][a-zA-Z0-9]{0,14}$"
    visible: ${create_vcn}

# CP SUBNET

  create_cp_subnet:
    title: "Create Control Plane subnet"
    description: "If flagged, this Terraform module will create the Kubernetes Control Plane subnet"
    type: boolean
    visible: ${create_vcn}

  cp_subnet_name:
    title: "Kubernetes Control Plane subnet name"
    description: "Name of the subnet containing the Kubernetes Control Plane API Server"
    type: string
    required: true
    visible:
      and:
        - ${create_cp_subnet}
        - ${create_vcn}

  cp_subnet_private:
    title: "Control Plane subnet is private"
    description: "Flag this if the Control Plane subnet is supposed to be private"
    type: boolean
    visible:
      and:
        - ${create_cp_subnet}
        - ${create_vcn}

  cp_allowed_source_cidr:
    title: "Control Plane allowed source cidr"
    description: "This source CIDR block will be able to contact the OKE API server"
    type: string
    pattern: "^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\/(?:[0-9]|[1-2][0-9]|3[0-2])$"
    required: true


# WORKER SUBNET

  create_worker_subnet:
    title: "Create Worker subnet"
    description: "If flagged, this Terraform module will create the Kubernetes Worker subnet"
    type: boolean
    visible: ${create_vcn}

  worker_subnet_name:
    title: "Worker subnet name"
    description: "Name of the Worker subnet"
    type: string
    required: true
    visible:
      and:
        - ${create_worker_subnet}
        - ${create_vcn}

  allow_worker_nat_egress:
    title: "Allow outbound traffic via NAT"
    description: "Allow worker node to reach external Internet through a NAT"
    type: boolean

# POD SUBNET

  create_pod_subnet:
    title: "Create Pod subnet"
    description: "If flagged, this Terraform module will create the Kubernetes Pod subnet"
    type: boolean
    visible:
      and:
        - ${create_vcn}
        - eq:
            - ${cni_type}
            - vcn_native


  pod_subnet_name:
    title: "Pod subnet name"
    description: "OKE pods will have an IP address assigned from this subnet"
    type: string
    required: true
    visible:
      and:
        - ${create_pod_subnet}
        - ${create_vcn}
        - eq:
            - ${cni_type}
            - vcn_native

  allow_pod_nat_egress:
    title: "Allow outbound traffic via NAT"
    description: "Allow pods to reach external Internet through a NAT"
    type: boolean
    visible:
      eq:
        - ${cni_type}
        - vcn_native

# LB SUBNETS

  create_external_lb_subnet:
    title: "Create external LB subnet"
    description: "If flagged, create a LB subnet to host publicly exposed services"
    type: boolean
    visible: ${create_vcn}

  external_lb_subnet_name:
    title: "Service subnet name"
    description: "Name of the external LB subnet"
    type: string
    required: true
    visible:
      and:
        - ${create_external_lb_subnet}
        - ${create_vcn}

  create_internal_lb_subnet:
    title: "Create internal LB subnet"
    description: "If flagged, create a LB subnet to host internally exposed services"
    type: boolean
    visible: ${create_vcn}

  internal_lb_subnet_name:
    title: "Service subnet name"
    description: "Name of the internal LB subnet"
    type: string
    required: true
    visible:
      and:
        - ${create_internal_lb_subnet}
        - ${create_vcn}

# FSS SUBNET

  create_fss:
    title: "Create FSS subnet"
    description: "Create a subnet for the File System Storage service"
    type: boolean
    visible: ${create_vcn}

  fss_subnet_name:
    title: "FSS subnet name"
    description: "Name of the FSS subnet to create"
    required: true
    visible:
      and:
        - ${create_fss}
        - ${create_vcn}

# BASTION SUBNET

  create_bastion_subnet:
    title: "Create Bastion Subnet"
    description: "If flagged, the Stack creates the Bastion Subnet"
    type: boolean
    visible: ${create_vcn}

  bastion_subnet_name:
    title: "Bastion subnet name"
    description: "Name of the subnet for Bastions"
    type: string
    required: true
    visible:
      and:
        - ${create_bastion_subnet}
        - ${create_vcn}

  bastion_subnet_private:
    title: "Bastion subnet is private"
    description: "Note that if you use the OCI Bastion, the bastion subnet can also be private"
    type: boolean
    visible:
      and:
        - ${create_bastion_subnet}
        - ${create_vcn}


# VCN GATEWAYS

  create_gateways:
    title: "Create Gateways"
    description: "Create both NAT and Service Gateways"
    type: boolean
    default: true
    visible:
      not:
        - ${create_vcn}

  create_internet_gateway:
    title: "Create Internet Gateway"
    description: "Create also an Internet Gateway"
    type: boolean
    visible:
      and:
        - ${create_gateways}
        - not:
            - ${create_vcn}


# CONTROL PLANE EXTERNAL CONNECTION
  cp_connection_notice:
    title: "NOTICE"
    type: text
    multiline: true
    default: "The OKE Control Plane sometimes requires connection to Internet, and so it requires a NAT for some use cases.\nOne of this use case is to integrate OKE with an external OIDC Identity Provider.\nYou have here the option to choose between having a NAT or only enable routing for the required Service Gateway"
    required: false

  cp_external_nat:
    title: "Allow outbound traffic via NAT"
    description: "Allow the OKE control plane to reach external Internet through a NAT"
    type: boolean
    visible:
      and:
        - ${cp_subnet_private}
        - ${create_cp_subnet}

  allow_external_cp_traffic:
    title: "Allow external traffic"
    description: "Allow external traffic from the Control Plane"
    type: boolean
    visible:
      or:
        - not:
            - ${create_cp_subnet}
        - or:
          - not:
              - ${cp_subnet_private}
          - ${cp_external_nat}

  cp_egress_cidr:
    title: "Control Plane allowed egress cidr"
    description: "Allowed egress IP range that the Control Plane is allowed to call"
    type: string
    required: true
    pattern: "^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\/(?:[0-9]|[1-2][0-9]|3[0-2])$"
    visible:
      and:
        - ${allow_external_cp_traffic}
        - or:
            - not:
                - ${cp_subnet_private}
            - ${cp_external_nat}

# ADDITIONAL NETWORK

  create_db_subnet:
    title: "Create Database Subnet"
    description: "Create a subnet for all databases"
    type: boolean
    visible: ${create_vcn}

  db_subnet_name:
    title: "Database subnet name"
    description: "Name of the subnet for databases"
    type: string
    required: true
    visible:
      and:
        - ${create_db_subnet}
        - ${create_vcn}

  db_service_list:
    title: "Additional Database Services"
    description: "Create network rules for additional database services you are planning to use"
    type: enum
    additionalProps:
      allowMultiple: true
    enum:
      - postgres
      - cache
      - oracledb
    required: false
    default: []

  separate_db_nsg:
    title: "Create Separate database NSGs"
    description: "Create separate database NSGs to manually select which applications will be granted access to the database"
    type: boolean


# DRG

  enable_drg:
    title: "Enable DRG"
    description: "Enable DRG support for this VCN"
    type: boolean

  create_drg:
    title: "Create DRG"
    description: "Create a new DRG"
    type: boolean
    visible: ${enable_drg}

  drg_id:
    title: "DRG ID"
    description: "Existing DRG ID"
    type: string
    required: true
    visible:
      and:
        - ${enable_drg}
        - not:
            - ${create_drg}

  drg_name:
    title: "DRG name"
    description: "Name for the DRG to be created"
    type: string
    required: true
    visible:
      and:
        - ${enable_drg}
        - ${create_drg}

  create_drg_attachment:
    title: "Create DRG attachment"
    description: "Attach the DRG to this VCN"
    type: boolean
    visible:
      and:
        - ${enable_drg}
        - ${create_vcn}

  peer_vcns:
    title: "Peer VCN CIDR blocks"
    description: "A routing rule will be created on all private subnets to route traffic directed to these CIDR blocks to the DRG"
    type: array
    items:
      type: string
      pattern: "^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\/(?:[0-9]|[1-2][0-9]|3[0-2])$"
    required: false
    visible:
      and:
        - ${enable_drg}
        - ${create_vcn}
        - ${create_drg_attachment}

  tag_value:
    type: oci:identity:tag:value
    title: Tags
