apiVersion: functions.oci.oracle.com/v1alpha1
kind: Function
metadata:
  name: existing-hello
  labels:
    demo: oci-functions-operator-fake
spec:
  mode: Existing
  functionId: ocid1.fnfunc.oc1.iad.exampleuniqueid
  invokeEndpoint: https://functions.us-ashburn-1.oci.oraclecloud.com
