resource "oci_devops_deploy_artifact" "flux_operator_chart" {
  argument_substitution_mode = "NONE"
  deploy_artifact_source {
    chart_url                   = "oci://${local.region_key}.ocir.io/${local.namespace}/${var.ocir_repo_path_prefix}/charts/flux-operator"
    deploy_artifact_source_type = "HELM_CHART"
    deploy_artifact_version     = "$${chart_version}"
    helm_verification_key_source {
      verification_key_source_type = "NONE"
    }
  }
  deploy_artifact_type = "HELM_CHART"
  description          = "Location to the internal flux-operator chart generated by the build pipeline"
  display_name         = "flux-operator-chart"
  project_id           = oci_devops_project.devops_project.id
  count                = var.gitops_agent == "fluxcd" ? 1 : 0
}

resource "oci_devops_deploy_artifact" "flux_operator_values" {
  argument_substitution_mode = "SUBSTITUTE_PLACEHOLDERS"
  deploy_artifact_source {
    base64encoded_content       = file("${path.root}/templates/flux-operator-values.yaml")
    deploy_artifact_source_type = "INLINE"
  }
  deploy_artifact_type = "GENERIC_FILE"
  description          = "Values of the flux-operator Helm Chart"
  display_name         = "flux-operator-chart-values"
  project_id           = oci_devops_project.devops_project.id
  count                = var.gitops_agent == "fluxcd" ? 1 : 0
}

resource "oci_devops_deploy_artifact" "argocd_operator_chart" {
  argument_substitution_mode = "NONE"
  deploy_artifact_source {
    chart_url                   = "oci://${local.region_key}.ocir.io/${local.namespace}/${var.ocir_repo_path_prefix}/charts/argo-cd"
    deploy_artifact_source_type = "HELM_CHART"
    deploy_artifact_version     = "$${chart_version}"
    helm_verification_key_source {
      verification_key_source_type = "NONE"
    }
  }
  deploy_artifact_type = "HELM_CHART"
  description          = "Location to the internal argo-cd chart generated by the build pipeline"
  display_name         = "argo-cd-chart"
  project_id           = oci_devops_project.devops_project.id
  count                = var.gitops_agent == "argocd" ? 1 : 0
}

resource "oci_devops_deploy_artifact" "argocd_operator_values" {
  argument_substitution_mode = "SUBSTITUTE_PLACEHOLDERS"
  deploy_artifact_source {
    base64encoded_content       = file("${path.root}/templates/argocd-values.yaml")
    deploy_artifact_source_type = "INLINE"
  }
  deploy_artifact_type = "GENERIC_FILE"
  description          = "Values of the argo-cd Helm Chart"
  display_name         = "argo-cd-values"
  project_id           = oci_devops_project.devops_project.id
  count                = var.gitops_agent == "argocd" ? 1 : 0
}

resource "oci_devops_deploy_artifact" "gitops_bootstrap_prepare" {
  argument_substitution_mode = "NONE"
  deploy_artifact_source {
    base64encoded_content = templatefile("${path.root}/templates/gitops-bootstrap-prepare.yaml.tpl", {
      region                  = var.region
      oke_cluster_id          = "$${target_cluster_id}"
      kube_endpoint           = local.kube_endpoint
      gitops_agent            = var.gitops_agent
      gitops_namespace        = local.gitops_namespace
      ocir_registry           = "${local.region_key}.ocir.io"
      ocir_chart_repository   = "${local.region_key}.ocir.io/${local.namespace}/${var.ocir_repo_path_prefix}/charts"
      legacy_git_username     = var.git_username
      legacy_ocir_username    = local.legacy_ocir_username
      cluster_config_repo_url = var.gitops_agent == "fluxcd" ? oci_devops_repository.cluster_config_repo_flux[0].http_url : oci_devops_repository.cluster_config_repo_argocd[0].http_url
      apps_config_repo_url    = var.gitops_agent == "fluxcd" ? oci_devops_repository.apps_config_repo_flux[0].http_url : oci_devops_repository.apps_config_repo_argocd[0].http_url
      fleet_config_repo_url   = var.enable_multicluster ? oci_devops_repository.fleet_config_repo[0].http_url : ""
    })
    deploy_artifact_source_type = "INLINE"
  }
  deploy_artifact_type = "COMMAND_SPEC"
  description          = "Reusable command spec that prepares an explicitly selected OKE cluster with Vault-backed Git and OCIR credentials"
  display_name         = "gitops-bootstrap-prepare"
  project_id           = oci_devops_project.devops_project.id
}
