resource oci_devops_deploy_artifact flux_operator_chart {
  argument_substitution_mode = "NONE"
  deploy_artifact_source {
    chart_url = "oci://${local.region_key}.ocir.io/${local.namespace}/${var.ocir_repo_path_prefix}/helm/flux-operator"
    deploy_artifact_source_type = "HELM_CHART"
    deploy_artifact_version     = "$${chart_version}"
    helm_verification_key_source {
      verification_key_source_type = "NONE"
    }
  }
  deploy_artifact_type = "HELM_CHART"
  description          = "Location to the internal flux-operator chart generated by the build pipeline"
  display_name         = "flux-operator-chart"
  project_id = oci_devops_project.devops_project.id
}

resource oci_devops_deploy_artifact flux_operator_values {
  argument_substitution_mode = "SUBSTITUTE_PLACEHOLDERS"
  deploy_artifact_source {
    base64encoded_content = filebase64("${path.root}/templates/flux-operator-values.yaml")
    deploy_artifact_source_type = "INLINE"
  }
  deploy_artifact_type = "GENERIC_FILE"
  description          = "Values of the flux-operator Helm Chart"
  display_name         = "flux-operator-chart-values"
  project_id = oci_devops_project.devops_project.id
}
