apiVersion: v1
kind: LimitRange
metadata:
  name: reference-app-defaults
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 20m
        memory: 32Mi
      default:
        cpu: 200m
        memory: 128Mi
