apiVersion: v1
kind: ResourceQuota
metadata:
  name: reference-app
spec:
  hard:
    pods: "10"
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    persistentvolumeclaims: "0"
    requests.storage: "0"
