apiVersion: v2
name: oci-functions-operator
description: Kubernetes operator for managing and invoking OCI Functions from OKE
type: application
version: 0.1.0
appVersion: "mvp-events-functionevents-v1"
keywords:
- oci
- functions
- oke
- operator
home: https://github.com/ronsevetoci/oci-functions-operator
sources:
- https://github.com/ronsevetoci/oci-functions-operator
