/*
 Select AI - Database Log Analyser Agent
*/


/*
Pre-Requisites - Configuring Select AI
*/


/*
Note: Please refer to "00 - Setup Select AI - Anon" for all pre-requisites on granting permissions to Packages, LLMs, Authentication and for Setting Up Credentials.
*/


/*
Create a Database Log Analyser Agent
*/


/*
This example shows how you can create an agent team using three agents-task pairs to retrieve logs, analyze them and then send out an email notification summarising the report.

Create Agents

* Create the agent called DATA_ENGINEER_AGENT with the role to retrieve and process complex data.

* Create the agent called OPS_MANAGER_AGENT with the role to analyze the data.

* Create the agent called EMAIL_LOG_REPORT_AGENT with the role to send an email notification

Create Tools

* Create an agent tool LOG_FETCHER_TOOL returns log entries after a given date. This uses a custom procedure fetch_logs.

* Create an agent tool LOG_REPORT_EMAIL_TOOL send an email notification.

Create Tasks

You define three tasks FETCH_LOGS_TASK, ANALYZE_LOGS_TASK and EMAIL_LOGS_REPORT_TASK to guide the flow.

* The FETCH_LOGS_TASK calls LOG_FETCHER_TOOL to retrieve logs based on the request.

* The ANALYZE_LOGS_TASK analyzes the fetched logs.

* The EMAIL_LOG_REPORT_TASK calls LOG_REPORT_EMAIL_TOOL to send an email notification.

Create Agent Team

You create OPS_ISSUES_SOLUTION_TEAM team with DATA_ENGINEER_AGENT, OPS_MANAGER_AGENT and EMAIL_LOG_REPORT_AGENT to run sequentially.
*/


/*
Drop Table
*/


-- Drop Table
DROP TABLE IF EXISTS DEMO_AGENTS_APP_LOGS;


/*
Create Tables & Insert Records
*/


-- Create Table for Sample Data
CREATE TABLE DEMO_AGENTS_APP_LOGS (
  log_id         NUMBER GENERATED BY DEFAULT AS IDENTITY,
  log_timestamp  DATE,
  log_message    VARCHAR2(4000)
);

-- Insert Dummy Records
INSERT INTO DEMO_AGENTS_APP_LOGS (log_timestamp, log_message) VALUES (
  TO_DATE('2025-03-22 03:15:45', 'YYYY-MM-DD HH24:MI:SS'),
  'INFO: Database Cluster: Failover completed successfully. Standby promoted to primary. Downtime duration: 33 seconds. Correlation ID: dbfailover102.'
);

-- Insert Dummy Records
INSERT INTO DEMO_AGENTS_APP_LOGS (log_timestamp, log_message) VALUES (
  TO_DATE('2025-03-23 08:44:10', 'YYYY-MM-DD HH24:MI:SS'),
  'INFO: Switchover Process: Synchronization restored. Performing scheduled switchover. Correlation ID: dbswitchover215.'
);

-- Insert Dummy Records
INSERT INTO DEMO_AGENTS_APP_LOGS (log_timestamp, log_message) VALUES (
  TO_DATE('2025-03-24 03:15:12', 'YYYY-MM-DD HH24:MI:SS'),
  'ERROR: Database Cluster: Primary database unreachable, initiating failover to standby. Correlation ID: dbfailover102.'
);

-- Commit Records
COMMIT;


/*
Define OCI API Credential
*/


-- Drop Credential
BEGIN
    DBMS_CLOUD.DROP_CREDENTIAL('<enter-oci-api-credential-name>');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Credential does not exist.');
END;
/


-- Create Credentials for OCI API Key
BEGIN                                                                          
	DBMS_CLOUD.CREATE_CREDENTIAL
        (  
		    	credential_name => '<enter-oci-api-credential-name>',
			 	user_ocid 		=> '<enter-user-ocid>',
		        tenancy_ocid    => '<enter-tenancy-ocid>',
		        private_key     => '<enter-private-key-value>',
		        fingerprint     => '<enter-private-key-fingerprint>'       
        );                                                                           
END;                                                                           
/


/*
Drop AI Profile
*/


-- Drop AI Profile
BEGIN
    DBMS_CLOUD_AI.DROP_PROFILE('<enter-ai-profile-name>');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Profile does not exist.');
END;
/


/*
Create AI Profile
*/


-- Create AI Profile on Log Table
BEGIN                                                                          
	DBMS_CLOUD_AI.CREATE_PROFILE
        (                                                
		        profile_name => '<enter-ai-profile-name>'
		    ,   attributes   => '{
                                        "provider"          : "oci"
		                    ,   "object_list"       : 
                                                                [
                                                                        {"owner": "<enter-schema-name>", "name": "DEMO_AGENTS_APP_LOGS"}
                                                                ]
                                    ,   "credential_name"   : "<enter-oci-api-credential-name>"
                                    ,   "model"             : "<enter-model-name-id>"
                                    ,   "oci_compartment_id": "<enter-compartment-ocid>"
                                    ,   "region"            : "<enter-region-identifier>"
                                    ,   "temperature"       : 0.2
                                    ,   "max_tokens"        : 2048
                                    ,   "comments"          : "true"
                                    ,   "conversation"      : "true"
                                }'
        );
END;                                                                           
/


/*
Drop Agents
*/


-- Drop Agents
BEGIN
    DBMS_CLOUD_AI_AGENT.DROP_AGENT('DATA_ENGINEER_AGENT');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Agent does not exist.');
END;
/

BEGIN
    DBMS_CLOUD_AI_AGENT.DROP_AGENT('OPS_MANAGER_AGENT');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Agent does not exist.');
END;
/

BEGIN
    DBMS_CLOUD_AI_AGENT.DROP_AGENT('EMAIL_LOG_REPORT_AGENT');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Agent does not exist.');
END;
/


/*
Create Agents
*/


BEGIN

    -- Create Data Engineer Agent
    DBMS_CLOUD_AI_AGENT.CREATE_AGENT(
        agent_name => 'DATA_ENGINEER_AGENT',
        attributes => '{"profile_name": "<enter-ai-profile-name>",
                        "role": "You are a specialized data ingestion engineer with expertise in   ' ||
                        'retrieving and processing data from complex database systems."
        }'
    );

    -- Create Ops Manager Agent
    DBMS_CLOUD_AI_AGENT.CREATE_AGENT(
        agent_name => 'OPS_MANAGER_AGENT',
        attributes => '{"profile_name": "<enter-ai-profile-name>",
                        "role": "You are an experienced Ops manager who excels at analyzing ' ||
                        'complex log data, diagnosing the issues."
         }'
    );

    -- Create Email Log Report Agent
    DBMS_CLOUD_AI_AGENT.CREATE_AGENT(
        agent_name => 'EMAIL_LOG_REPORT_AGENT',
        attributes => '{"profile_name": "<enter-ai-profile-name>",
                        "role": "You are a specialized email writer which recieves an analysed log report ' ||
                        'which you must send to the Database Operations Team."
         }'
    );

END;
/


/*
Drop Log Fetcher Function
*/


-- Drop Function for fecthing logs
DROP FUNCTION IF EXISTS fetch_logs;


/*
Create PL/SQL Function to Fetch Logs
*/


-- Create a customized fetch_logs procedure
CREATE OR REPLACE FUNCTION fetch_logs(since_date IN DATE) RETURN CLOB AS
  
  -- Declare variable
  l_logs CLOB;

  BEGIN
    SELECT JSON_ARRAYAGG(log_message RETURNING CLOB)
      INTO l_logs
    FROM demo_agents_app_logs
    WHERE log_timestamp >= since_date
    ORDER BY log_timestamp;

    RETURN l_logs;

  EXCEPTION
    WHEN OTHERS THEN
      RETURN 'Error fetching logs: ' || SQLERRM;

END fetch_logs;
/


/*
Drop Log Fetcher Tool
*/


-- Drop Log Fetcher Tool
BEGIN
    DBMS_CLOUD_AI_AGENT.DROP_TOOL('LOG_FETCHER_TOOL');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Tool does not exist.');
END;
/


/*
Create Log Fetcher Tool
*/


--Create Log Fetcher Tool
BEGIN
    DBMS_CLOUD_AI_AGENT.CREATE_TOOL(
    tool_name => 'LOG_FETCHER_TOOL',
    attributes => '{"instruction": "retrieves and returns all log messages with a LOG_TIMESTAMP greater than or equal to the input date.",
                    "function": "fetch_logs"}'
    );
END;
/


/*
Define SMTP Credential
*/


-- Drop Credential
BEGIN
    DBMS_CLOUD.DROP_CREDENTIAL('<enter-smtp-credential-name>');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Credential does not exist.');
END;
/


-- Create Credential for SMTP Credentials
BEGIN
  DBMS_CLOUD.CREATE_CREDENTIAL(
    credential_name => '<enter-smtp-credential-name>',
    username => '<enter-smtp-credential-username>',
    password => '<enter-smtp-credential-password>');
END;
/
 

/*
Enable ACL to Communicate with SMTP Server
*/


-- Enable ACL to communicate with SMTP Server
BEGIN
   DBMS_NETWORK_ACL_ADMIN.APPEND_HOST_ACE(
     host => '<smtp-server-region-identifier>',
     lower_port => 587,
     upper_port => 587,
     ace => xs$ace_type(privilege_list => xs$name_list('SMTP'),
                        principal_name => '<schema-name>',
                        principal_type => xs_acl.ptype_db));
END;
/


/*
Drop Email Notification Tool
*/


-- Drop Email Notification Tool
BEGIN
    DBMS_CLOUD_AI_AGENT.DROP_TOOL('LOG_REPORT_EMAIL_TOOL');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Tool does not exist.');
END;
/


/*
Create Email Notification Tool
*/


-- Create Email Notification Tool
BEGIN
  DBMS_CLOUD_AI_AGENT.CREATE_TOOL(
    tool_name  => 'LOG_REPORT_EMAIL_TOOL',
    attributes => '{"instruction": "This tool allows you to send an email to the DB Operations Team.",
                    "tool_type": "NOTIFICATION",
                    "tool_params": {"notification_type" : "EMAIL",
                                    "credential_name": "<enter-smtp-credential-name>",
                                    "recipient": "<enter-recipient-email-address>",
                                    "smtp_host": "<enter-smtp-host-name>",
                                    "sender": "<enter-approved-sender-email-address>"
                      }
                  }'
  );
END;
/
 

/*
Drop Fetch Logs Task
*/


-- Drop Fetch Logs Task
BEGIN
    DBMS_CLOUD_AI_AGENT.DROP_TASK('FETCH_LOGS_TASK');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Task does not exist.');
END;
/


/*
Create Fetch Logs Task
*/


--Create Fetch Logs Task
BEGIN
    DBMS_CLOUD_AI_AGENT.CREATE_TASK(
      task_name  => 'FETCH_LOGS_TASK',
      attributes => '{"instruction": "Fetch the log entries from the database based on user request: {query}.",
                      "tools": ["LOG_FETCHER_TOOL"]
      }'
    );
END;
/


/*
Drop Analyse Logs Task
*/


-- Drop Analyse Logs Task
BEGIN
    DBMS_CLOUD_AI_AGENT.DROP_TASK('ANALYZE_LOGS_TASK');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Task does not exist.');
END;
/


/*
Create Analyse Logs Task
*/


-- Create Analyse Log Task
BEGIN
  DBMS_CLOUD_AI_AGENT.create_task(
    task_name => 'ANALYZE_LOGS_TASK',
    attributes => '{"instruction": "You are responsible to analyze the following fetched log entries: {query} ' ||
                  'Generate a report for the database operations team that includes your issue analysis and possible solutions to resolve the issues.",
        "input" : "FETCH_LOGS_TASK"
    }'
  );
END;
/


/*
Drop Email Notification Task
*/


-- Drop Email Notification Task
BEGIN
    DBMS_CLOUD_AI_AGENT.DROP_TASK('EMAIL_LOGS_REPORT_TASK');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Task does not exist.');
END;
/


/*
Create Email Notification Task
*/


-- Create Email Notification Task
BEGIN
  DBMS_CLOUD_AI_AGENT.create_task(
    task_name => 'EMAIL_LOGS_REPORT_TASK',
    attributes => '{"instruction": "Send an email to the DB Operations team containing the following report: {query} ' ||
                  'Start the email with - Hi DB Operations Team,\n' ||
                  'End the email with - \nMany thanks,\nIssy and Thomas",
        "input" : "ANALYZE_LOGS_TASK",
        "tools": ["LOG_REPORT_EMAIL_TOOL"]
    }'
  );
END;
/


/*
Drop Agent Team
*/


-- Drop Agents Team
BEGIN
    DBMS_CLOUD_AI_AGENT.DROP_TEAM('OPS_ISSUES_SOLUTION_TEAM');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Agent Team does not exist.');
END;
/


/*
Create Agent Team
*/


-- Create Agent Team
BEGIN
  DBMS_CLOUD_AI_AGENT.create_team(
    team_name  => 'OPS_ISSUES_SOLUTION_TEAM',
    attributes => '{"agents": [{"name":"DATA_ENGINEER_AGENT","task" : "FETCH_LOGS_TASK"},
                                {"name":"OPS_MANAGER_AGENT","task" : "ANALYZE_LOGS_TASK"},
                                {"name":"EMAIL_LOG_REPORT_AGENT", "task" : "EMAIL_LOGS_REPORT_TASK"}],
                    "process": "sequential"
      }'
  );
END;
/


/*
Set Agent Team
*/


-- Set Agent Team
BEGIN
    DBMS_CLOUD_AI_AGENT.SET_TEAM('OPS_ISSUES_SOLUTION_TEAM');
END;
/


/*
Validate Agent Team is in Session
*/


-- Validate Agent Team in Session
SELECT DBMS_CLOUD_AI_AGENT.GET_TEAM FROM DUAL;


/*
Interact with Agent Team
*/


-- Initiate Agent
select ai agent fetch and analyze the logs after 2025-03-20;

/*
View Tool History
*/


-- View the tool history
SELECT 
    * 
FROM 
    USER_AI_AGENT_TOOL_HISTORY
ORDER BY
    START_DATE DESC;


/*
View Task History
*/


-- View the task history
SELECT
    * 
FROM
    USER_AI_AGENT_TASK_HISTORY
ORDER BY 
    START_DATE DESC;

/*
View Team History
*/


-- View the team history
SELECT
    * 
FROM 
    USER_AI_AGENT_TEAM_HISTORY
ORDER BY
    START_DATE DESC;


/*
 End of Notebook
*/

