apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mpi-setup
  namespace: default
data:
  MPI_ARGS:
    -mca coll ^hcoll -mca coll_hcoll_enable 0
    -x NCCL_CROSS_NIC=2
    -x NCCL_SOCKET_NTHREADS=16
    -x NCCL_DEBUG=WARN
    -x NCCL_CUMEM_ENABLE=0
    -x NCCL_IB_SPLIT_DATA_ON_QPS=0
    -x NCCL_IB_QPS_PER_CONNECTION=16
    -x NCCL_IB_GID_INDEX=3
    -x NCCL_IB_HCA==mlx5_0,mlx5_1,mlx5_3,mlx5_4,mlx5_5,mlx5_6,mlx5_7,mlx5_8,mlx5_9,mlx5_10,mlx5_12,mlx5_13,mlx5_14,mlx5_15,mlx5_16,mlx5_17
    -x NCCL_IB_TC=41
    -x NCCL_IB_SL=0
    -x NCCL_IB_TIMEOUT=22
    -x HCOLL_ENABLE_MCAST_ALL=0
    -x UCX_TLS=tcp
    -x UCX_NET_DEVICES=eth0
    -x RX_QUEUE_LEN=8192
    -x IB_RX_QUEUE_LEN=8192
    -x NCCL_SOCKET_IFNAME=eth0
    -x NCCL_IGNORE_CPU_AFFINITY=1
