## This configuration was generated by terraform-provider-oci

resource oci_ons_notification_topic export_devopstopic {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  
  #description = <<Optional value not found in discovery>>
  freeform_tags = {
  }
  name = "${var.project_name}-devopstopic"
}

