#!/bin/bash
#######################################
# OCI Management Agent Installation Script
# Auto-generated by Terraform
#######################################

set -e

# Configuration
INSTALL_KEY="${install_key}"
REGION="${region}"
COMPARTMENT_OCID="${compartment_ocid}"
AGENT_VERSION="${agent_version}"
INSTALL_DIR="${install_dir}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "$${GREEN}===========================================\033[0m"
echo -e "$${GREEN}OCI Management Agent Installation\033[0m"
echo -e "$${GREEN}===========================================\033[0m"

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo -e "$${RED}Error: This script must be run as root\033[0m"
    exit 1
fi

# Detect OS
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$ID
    OS_VERSION=$VERSION_ID
else
    echo -e "$${RED}Error: Cannot detect OS\033[0m"
    exit 1
fi

echo -e "$${GREEN}Detected OS: $OS $OS_VERSION\033[0m"

# Create installation directory
mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"

# Download agent installer based on OS
echo -e "$${YELLOW}Downloading Management Agent installer...\033[0m"

if [ "$OS" = "ol" ] || [ "$OS" = "centos" ] || [ "$OS" = "rhel" ]; then
    # Oracle Linux / RHEL / CentOS
    INSTALLER_URL="https://objectstorage.$REGION.oraclecloud.com/n/idtskf8cjzhp/b/installer/o/Windows/latest/oracle.mgmt_agent.rpm"
    INSTALLER_FILE="oracle.mgmt_agent.rpm"
    INSTALL_CMD="rpm -ivh"
elif [ "$OS" = "ubuntu" ] || [ "$OS" = "debian" ]; then
    # Ubuntu / Debian
    INSTALLER_URL="https://objectstorage.$REGION.oraclecloud.com/n/idtskf8cjzhp/b/installer/o/Linux/latest/oracle.mgmt_agent.deb"
    INSTALLER_FILE="oracle.mgmt_agent.deb"
    INSTALL_CMD="dpkg -i"
else
    echo -e "$${RED}Error: Unsupported OS: $OS\033[0m"
    exit 1
fi

# Download installer
if command -v wget &> /dev/null; then
    wget -q "$INSTALLER_URL" -O "$INSTALLER_FILE"
elif command -v curl &> /dev/null; then
    curl -s -o "$INSTALLER_FILE" "$INSTALLER_URL"
else
    echo -e "$${RED}Error: Neither wget nor curl is available\033[0m"
    exit 1
fi

# Install agent
echo -e "$${YELLOW}Installing Management Agent...\033[0m"
$INSTALL_CMD "$INSTALLER_FILE"

# Configure agent
echo -e "$${YELLOW}Configuring Management Agent...\033[0m"

# Create input.rsp file
cat > /tmp/input.rsp <<EOF
ManagementAgentInstallKey=$INSTALL_KEY
AgentDisplayName=$(hostname)-mgmt-agent
CredentialWalletPassword=$(openssl rand -base64 32)
Service.plugin.prometheus.download=true
EOF

# Setup agent
/opt/oracle/mgmt_agent/agent_inst/bin/setup.sh opts=/tmp/input.rsp

# Start agent service
echo -e "$${YELLOW}Starting Management Agent service...\033[0m"
systemctl enable mgmt_agent
systemctl start mgmt_agent

# Wait for agent to register
echo -e "$${YELLOW}Waiting for agent to register with OCI...\033[0m"
sleep 30

# Check agent status
if systemctl is-active --quiet mgmt_agent; then
    echo -e "$${GREEN}Management Agent installed and running successfully!\033[0m"
    systemctl status mgmt_agent --no-pager
else
    echo -e "$${RED}Error: Management Agent failed to start\033[0m"
    systemctl status mgmt_agent --no-pager
    exit 1
fi

# Cleanup
rm -f /tmp/input.rsp
rm -f "$INSTALLER_FILE"

echo -e "$${GREEN}===========================================\033[0m"
echo -e "$${GREEN}Installation completed successfully!\033[0m"
echo -e "$${GREEN}===========================================\033[0m"
