apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
%{ if manages_operator ~}
  - flux-operator.yml
%{ endif ~}
  - common.yml
%{ if activates_development ~}
  - development.yml
%{ endif ~}
