apiVersion: v1
kind: ResourceQuota
metadata:
  name: reference-app
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    pods: "10"
    services: "10"
    configmaps: "20"
    secrets: "20"
    persistentvolumeclaims: "0"
    requests.storage: "0"
