apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-proof
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: oci-vault
  target:
    name: vault-proof
    creationPolicy: Owner
  data:
    - secretKey: message
      remoteRef:
        key: <vault-secret-name>
