{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "oci-functions-operator.fullname" . }}
  labels:
    {{- include "oci-functions-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - functions.oci.oracle.com
  resources:
  - functionevents
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - functions.oci.oracle.com
  resources:
  - functioneventtriggers
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - functions.oci.oracle.com
  resources:
  - functioneventtriggers/finalizers
  - functionjobs/finalizers
  - functions/finalizers
  verbs:
  - update
- apiGroups:
  - functions.oci.oracle.com
  resources:
  - functionevents/status
  - functioneventtriggers/status
  - functionjobs/status
  - functions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - functions.oci.oracle.com
  resources:
  - functionjobs
  - functions
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "oci-functions-operator.fullname" . }}
  labels:
    {{- include "oci-functions-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "oci-functions-operator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "oci-functions-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "oci-functions-operator.fullname" . }}-leader-election
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oci-functions-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "oci-functions-operator.fullname" . }}-leader-election
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oci-functions-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "oci-functions-operator.fullname" . }}-leader-election
subjects:
- kind: ServiceAccount
  name: {{ include "oci-functions-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
