apiVersion: v1
kind: LimitRange
metadata:
  name: reference-app-defaults
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 10m
        memory: 32Mi
      default:
        cpu: 100m
        memory: 128Mi
      max:
        cpu: 500m
        memory: 512Mi
