cat bastionsession.py | sed 's/"ociconfigurations"/const.OCICONFIGURATIONS/'|\
sed 's/"OCIConfig"/const.OCICONFIG/'|\
sed 's/"sessionType"/const.SESSIONTYPE/'|\
sed 's/"bastionPublicKeyFile"/const.BASTIONPUBLICKEYFILE/'|\
sed 's/"pubkeyContent"/const.PUBKEYCONTENT/'|\
sed 's/"configFileName"/const.CONFIGFILENAME/'|\
sed 's/"profileName"/const.PROFILENAME/'|\
sed 's/"bastionOCID"/const.BASTIONOCID/'|\
sed 's/"targetOCID"/const.TARGETOCID/'|\
sed 's/"targetPort"/const.TARGETPORT/'|\
sed 's/"targetPrivateKeyFile"/const.TARGETPRIVATEKEYFILE/'|\
sed 's/"sessionDisplayName"/const.SESSIONDISPLAYNAME/'|\
sed 's/"timetolive"/const.TIMETOLIVE/'|\
sed 's/"maxWaitCount"/const./'|\
sed 's/"waitRefresh"/const.WAITREFRESH/'|\
sed 's/"command"/const.COMMAND/'|\
sed 's/"bastionPrivateKeyFile"/const.BASTIONPRIVATEKEYFILE/'|\
sed 's/"sshCommand"/const.SSHCOMMAND/'|\
sed 's/"localPort"/const.LOCALPORT/'|\
sed 's/"osUserName"/const.OSUSERNAME/'|\
sed 's/"clientside"/const.CLIENTSIDE/'|\
sed 's/"serverside"/const.SERVERSIDE/'|\
sed 's/"targetPrivateKeyFile"/const.TARGETPRIVATEKEYFILE/'|\
sed 's/"targetPort"/const.TARGETPORT/'|\
sed 's/"configName"/const.CONFIGNAME/'|\
sed 's/"configFileName"/const.CONFIGFILENAME/'|\
sed 's/"profileName"/const.PROFILENAME/'|\
sed 's/"maxSessions"/const.MAXSESSIONS/'|\
sed 's/"sessions"/const.SESSIONS/'|\
sed 's/"sessionConfig"/const.SESSIONCONFIG/'|\
sed 's/"cmdargs"/const.CMDARGS/'|\
sed 's/"exec"/const.EXEC/'>bas3.py

