TEMP=`cat bastionsession.py`
TEMP=`echo $TEMP | sed s/"session"/SESSION="session"/`
TEMP=`echo $TEMP | sed s/"sessionType"/SESSIONTYPE="sessionType"/`
TEMP=`echo $TEMP | sed s/"MANAGED_SSH"/MANAGED_SSH="MANAGED_SSH"/`
TEMP=`echo $TEMP | sed s/"ACTIVE"/ACTIVE="ACTIVE"/`
TEMP=`echo $TEMP | sed s/"PORT_FORWARDING"/PORT_FORWARDING="PORT_FORWARDING"/`
TEMP=`echo $TEMP | sed s/"bastionPublicKeyFile"/BASTIONPUBLICKEYFILE="bastionPublicKeyFile"/`
TEMP=`echo $TEMP | sed s/"bastionPrivateKeyFile"/BASTIONPRIVATEKEYFILE="bastionPrivateKeyFile"/`
TEMP=`echo $TEMP | sed s/"bastionOCID"/BASTIONOCID="bastionOCID"/`
TEMP=`echo $TEMP | sed s/"pubkeyContent"/PUBKEYCONTENT="pubkeyContent"/`
TEMP=`echo $TEMP | sed s/"OCIConfig"/OCICONFIG="OCIConfig"/`
TEMP=`echo $TEMP | sed s/"ociRegion"/OCIREGION="ociRegion"/`
TEMP=`echo $TEMP | sed s/"ociconfigurations"/OCICONFIGURATIONS="ociconfigurations"/`
TEMP=`echo $TEMP | sed s/"configFileName"/CONFIGFILENAME="configFileName"/`
TEMP=`echo $TEMP | sed s/"configName"/CONFIGNAME="configName"/`
TEMP=`echo $TEMP | sed s/"profileName"/PROFILENAME="profileName"/`
TEMP=`echo $TEMP | sed s/"sessions"/SESSIONS="sessions"/`
TEMP=`echo $TEMP | sed s/"sessionName"/SESSIONNAME="sessionName"/`
TEMP=`echo $TEMP | sed s/"profileName"/PROFILENAME="profileName"/`
TEMP=`echo $TEMP | sed s/"osUserName"/OSUSERNAME="osUserName"/`
TEMP=`echo $TEMP | sed s/"targetOCID"/TARGETOCID="targetOCID"/`
TEMP=`echo $TEMP | sed s/"targetPrivateIP"/TARGETPRIVATEIP="targetPrivateIP"/`
TEMP=`echo $TEMP | sed s/"targetPrivateKeyFile"/TARGETPRIVATEKEYFILE="targetPrivateKeyFile"/`
TEMP=`echo $TEMP | sed s/"targetPort"/TARGETPORT="targetPort"/`
TEMP=`echo $TEMP | sed s/"pubkeyContent"/PUBKEYCONTENT="pubkeyContent"/`
TEMP=`echo $TEMP | sed s/"sessionDisplayName"/SESSIONDISPLAYNAME="sessionDisplayName"/`
TEMP=`echo $TEMP | sed s/"sessionConfig"/SESSIONCONFIG="sessionConfig"/`
TEMP=`echo $TEMP | sed s/"PUB"/PUB="PUB"/`
TEMP=`echo $TEMP | sed s/"timetolive"/TIMETOLIVE="timetolive"/`
TEMP=`echo $TEMP | sed s/"maxWaitCount"/MAXWAITCOUNT="maxWaitCount"/`
TEMP=`echo $TEMP | sed s/"ACTIVE"/ACTIVE="ACTIVE"/`
TEMP=`echo $TEMP | sed s/"waitRefresh"/WAITREFRESH="waitRefresh"/`
TEMP=`echo $TEMP | sed s/"maxWaitCount"/MAXWAITCOUNT="maxWaitCount"/`
TEMP=`echo $TEMP | sed s/"maxSessions"/MAXSESSIONS="maxSessions"/`
TEMP=`echo $TEMP | sed s/"command"/COMMAND="command"/`
TEMP=`echo $TEMP | sed s/"<privateKey>"/<PRIVATEKEY>="<privateKey>"/`
TEMP=`echo $TEMP | sed s/"localPort"/LOCALPORT="localPort"/`
TEMP=`echo $TEMP | sed s/"sshCommand"/SSHCOMMAND="sshCommand"/`
TEMP=`echo $TEMP | sed s/"ssh"/SSH="ssh"/`
TEMP=`echo $TEMP | sed s/"putty"/PUTTY="putty"/`
TEMP=`echo $TEMP | sed s/"localPort"/LOCALPORT="localPort"/`
TEMP=`echo $TEMP | sed s/"osUserName"/OSUSERNAME="osUserName"/`
TEMP=`echo $TEMP | sed s/"clientside"/CLIENTSIDE="clientside"/`
TEMP=`echo $TEMP | sed s/"serverside"/SERVERSIDE="serverside"/`
TEMP=`echo $TEMP | sed s/"putty.exe"/PUTTY.EXE="putty.exe"/`
TEMP=`echo $TEMP | sed s/"cmdargs"/CMDARGS="cmdargs"/`
TEMP=`echo $TEMP | sed s/"exec"/EXEC="exec"/`
TEMP=`echo $TEMP | sed s/"cmdargs"/CMDARGS="cmdargs"/`
TEMP=`echo $TEMP | sed s/"bastionconfig"/BASTIONCONFIG="bastionconfig"/`
TEMP=`echo $TEMP | sed s/"linux"/LINUX="linux"/`
TEMP=`echo $TEMP | sed s/"windows"/WINDOWS="windows"/`
TEMP=`echo $TEMP | sed s/"Bastion sesssion manager"/BASTION SESSSION MANAGER="Bastion sesssion manager"/`
echo $TEMP >b.py
