apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      reconcile.fluxcd.io/watch: Enabled

resources:
  - ../test-dev-oci

configMapGenerator:
  - name: ${component}-values-${environment}-${profile}-oci-uk-london-1
    files:
      - values.yaml=./values.yml

generatorOptions:
  disableNameSuffixHash: true
