apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: enterprise-chat-app
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: ocir-credentials
      containers:
        - name: backend
          image: fra.ocir.io/froszmh35vv3/aiq/aiq-backend:v1
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secrets
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
          volumeMounts:
            - name: oracle-wallet
              mountPath: /app/config/wallet
              readOnly: true
      volumes:
        - name: oracle-wallet
          secret:
            secretName: oracle-wallet
