# A role specific for this namespace to be used by pods
# We let pods get, watch and list other pods in the same namespace
# Not all pods need this kind of restriction, and most of them do not even need to communicate with the Kubernetes API server at all
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-restricted
  namespace: example
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]