## This configuration was generated by terraform-provider-oci

resource oci_artifacts_container_configuration export_container_configuration {
  compartment_id                      = var.compartment_ocid
  is_repository_created_on_first_push = "true"
}

resource oci_artifacts_container_repository export_project {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.compartment_id
  
  display_name = "${var.project_name}-image"
  freeform_tags = {
  }
  is_immutable = "false"
  is_public    = "false"
}
