## This configuration was generated by terraform-provider-oci

resource oci_devops_deploy_pipeline export_project-native {
  
  #deploy_pipeline_parameters {
  #}
  description  = ""
  display_name = "${var.project_name}-native"
  freeform_tags = {
  }
  project_id = oci_devops_project.export_project.id
}

resource oci_devops_deploy_pipeline export_project-jvm {
  
  #deploy_pipeline_parameters {
  #}
  
  description  = ""
  display_name = "${var.project_name}-jvm"
  freeform_tags = {
  }
  project_id = oci_devops_project.export_project.id
}

resource oci_devops_deploy_environment export_fn {
  #cluster_id = <<Optional value not found in discovery>>
  #compute_instance_group_selectors = <<Optional value not found in discovery>>
  
  deploy_environment_type = "FUNCTION"
  description             = ""
  display_name            = "${var.project_name}"
  freeform_tags = {
  }
  function_id = oci_functions_function.export_project_2.id
  #network_channel = <<Optional value not found in discovery>>
  project_id = oci_devops_project.export_project.id
}

resource oci_devops_deploy_artifact export_project-native_1 {
  argument_substitution_mode = "SUBSTITUTE_PLACEHOLDERS"
  
  deploy_artifact_source {
    #base64encoded_content = <<Optional value not found in discovery>>
    #chart_url = <<Optional value not found in discovery>>
    #deploy_artifact_path = <<Optional value not found in discovery>>
    deploy_artifact_source_type = "OCIR"
    #deploy_artifact_version = <<Optional value not found in discovery>>
    #helm_artifact_source_type = <<Optional value not found in discovery>>
    #helm_verification_key_source = <<Optional value not found in discovery>>
    image_digest = ""
    image_uri    = "${var.registry}/${data.oci_objectstorage_namespace.tenancy_namespace.namespace}/${var.image_name}:$${buildId}"
    #repository_id = <<Optional value not found in discovery>>
  }
  deploy_artifact_type = "DOCKER_IMAGE"
  description          = ""
  display_name         = "${var.image_name}-native"
  freeform_tags = {
  }
  project_id = oci_devops_project.export_project.id
}

resource oci_devops_deploy_artifact export_project-jvm_1 {
  argument_substitution_mode = "SUBSTITUTE_PLACEHOLDERS"
  
  deploy_artifact_source {
    #base64encoded_content = <<Optional value not found in discovery>>
    #chart_url = <<Optional value not found in discovery>>
    #deploy_artifact_path = <<Optional value not found in discovery>>
    deploy_artifact_source_type = "OCIR"
    #deploy_artifact_version = <<Optional value not found in discovery>>
    #helm_artifact_source_type = <<Optional value not found in discovery>>
    #helm_verification_key_source = <<Optional value not found in discovery>>
    image_digest = ""
    image_uri    = "${var.registry}/${data.oci_objectstorage_namespace.tenancy_namespace.namespace}/${var.image_name}:$${buildId}"
    #repository_id = <<Optional value not found in discovery>>
  }
  deploy_artifact_type = "DOCKER_IMAGE"
  description          = ""
  display_name         = "${var.image_name}-jvm"
  freeform_tags = {
  }
  project_id = oci_devops_project.export_project.id
}

resource oci_devops_project export_project {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  
  description = "OCI DevOps for OCI Function in Java that uses GenAI OCI service"
  freeform_tags = {
  }
  name = "${var.project_name}"
  notification_config {
    topic_id = oci_ons_notification_topic.export_devopstopic.id
  }
}

resource oci_devops_build_pipeline export_project-native_2 {
  build_pipeline_parameters {
    items {
      name = "NAMESPACE"
      default_value = "${data.oci_objectstorage_namespace.tenancy_namespace.namespace}"
    }
    items {
      name = "REGISTRY"
      default_value = "${var.registry}"
    }
    items {
      name = "IMAGE_NAME"
      default_value = "${var.image_name}"
    }
  }
  
  description  = "Build of native image"
  display_name = "${var.project_name}-native"
  freeform_tags = {
  }
  project_id = oci_devops_project.export_project.id
}

resource oci_devops_build_pipeline export_project-jvm_2 {
  build_pipeline_parameters {
    items {
      name = "NAMESPACE"
      default_value = "${data.oci_objectstorage_namespace.tenancy_namespace.namespace}"
    }
    items {
      name = "REGISTRY"
      default_value = "${var.registry}"
    }
    items {
      name = "IMAGE_NAME"
      default_value = "${var.image_name}"
    }
  }
  
  description  = "Build of JVM image"
  display_name = "${var.project_name}-jvm"
  freeform_tags = {
  }
  project_id = oci_devops_project.export_project.id
}

resource oci_devops_deploy_stage export_deploy {
  #approval_policy = <<Optional value not found in discovery>>
  #are_hooks_enabled = <<Optional value not found in discovery>>
  #blue_backend_ips = <<Optional value not found in discovery>>
  #blue_green_strategy = <<Optional value not found in discovery>>
  #canary_strategy = <<Optional value not found in discovery>>
  #command_spec_deploy_artifact_id = <<Optional value not found in discovery>>
  #compute_instance_group_blue_green_deployment_deploy_stage_id = <<Optional value not found in discovery>>
  #compute_instance_group_canary_deploy_stage_id = <<Optional value not found in discovery>>
  #compute_instance_group_canary_traffic_shift_deploy_stage_id = <<Optional value not found in discovery>>
  #compute_instance_group_deploy_environment_id = <<Optional value not found in discovery>>
  config = {
  }
  #container_config = <<Optional value not found in discovery>>
  
  #deploy_artifact_id = <<Optional value not found in discovery>>
  #deploy_artifact_ids = <<Optional value not found in discovery>>
  #deploy_environment_id_a = <<Optional value not found in discovery>>
  #deploy_environment_id_b = <<Optional value not found in discovery>>
  deploy_pipeline_id = oci_devops_deploy_pipeline.export_project-native.id
  deploy_stage_predecessor_collection {
    items {
      id = oci_devops_deploy_pipeline.export_project-native.id
    }
  }
  deploy_stage_type = "DEPLOY_FUNCTION"
  #deployment_spec_deploy_artifact_id = <<Optional value not found in discovery>>
  description                     = ""
  display_name                    = "deploy"
  docker_image_deploy_artifact_id = oci_devops_deploy_artifact.export_project-native_1.id
  #failure_policy = <<Optional value not found in discovery>>
  freeform_tags = {
  }
  function_deploy_environment_id = oci_devops_deploy_environment.export_fn.id
  function_timeout_in_seconds    = "30"
  #green_backend_ips = <<Optional value not found in discovery>>
  #helm_chart_deploy_artifact_id = <<Optional value not found in discovery>>
  #helm_command_artifact_ids = <<Optional value not found in discovery>>
  #is_async = <<Optional value not found in discovery>>
  #is_debug_enabled = <<Optional value not found in discovery>>
  #is_force_enabled = <<Optional value not found in discovery>>
  #is_uninstall_on_stage_delete = <<Optional value not found in discovery>>
  #is_validation_enabled = <<Optional value not found in discovery>>
  #kubernetes_manifest_deploy_artifact_ids = <<Optional value not found in discovery>>
  #load_balancer_config = <<Optional value not found in discovery>>
  #max_history = <<Optional value not found in discovery>>
  max_memory_in_mbs = "512"
  #namespace = <<Optional value not found in discovery>>
  #oke_blue_green_deploy_stage_id = <<Optional value not found in discovery>>
  #oke_canary_deploy_stage_id = <<Optional value not found in discovery>>
  #oke_canary_traffic_shift_deploy_stage_id = <<Optional value not found in discovery>>
  #oke_cluster_deploy_environment_id = <<Optional value not found in discovery>>
  #production_load_balancer_config = <<Optional value not found in discovery>>
  #purpose = <<Optional value not found in discovery>>
  #release_name = <<Optional value not found in discovery>>
  #rollback_policy = <<Optional value not found in discovery>>
  #rollout_policy = <<Optional value not found in discovery>>
  #set_string = <<Optional value not found in discovery>>
  #set_values = <<Optional value not found in discovery>>
  #should_cleanup_on_fail = <<Optional value not found in discovery>>
  #should_not_wait = <<Optional value not found in discovery>>
  #should_reset_values = <<Optional value not found in discovery>>
  #should_reuse_values = <<Optional value not found in discovery>>
  #should_skip_crds = <<Optional value not found in discovery>>
  #should_skip_render_subchart_notes = <<Optional value not found in discovery>>
  #test_load_balancer_config = <<Optional value not found in discovery>>
  #timeout_in_seconds = <<Optional value not found in discovery>>
  #traffic_shift_target = <<Optional value not found in discovery>>
  #values_artifact_ids = <<Optional value not found in discovery>>
  #wait_criteria = <<Optional value not found in discovery>>
}

resource oci_devops_deploy_stage export_deploy_1 {
  #approval_policy = <<Optional value not found in discovery>>
  #are_hooks_enabled = <<Optional value not found in discovery>>
  #blue_backend_ips = <<Optional value not found in discovery>>
  #blue_green_strategy = <<Optional value not found in discovery>>
  #canary_strategy = <<Optional value not found in discovery>>
  #command_spec_deploy_artifact_id = <<Optional value not found in discovery>>
  #compute_instance_group_blue_green_deployment_deploy_stage_id = <<Optional value not found in discovery>>
  #compute_instance_group_canary_deploy_stage_id = <<Optional value not found in discovery>>
  #compute_instance_group_canary_traffic_shift_deploy_stage_id = <<Optional value not found in discovery>>
  #compute_instance_group_deploy_environment_id = <<Optional value not found in discovery>>
  config = {
  }
  #container_config = <<Optional value not found in discovery>>
  
  #deploy_artifact_id = <<Optional value not found in discovery>>
  #deploy_artifact_ids = <<Optional value not found in discovery>>
  #deploy_environment_id_a = <<Optional value not found in discovery>>
  #deploy_environment_id_b = <<Optional value not found in discovery>>
  deploy_pipeline_id = oci_devops_deploy_pipeline.export_project-jvm.id
  deploy_stage_predecessor_collection {
    items {
      id = oci_devops_deploy_pipeline.export_project-jvm.id
    }
  }
  deploy_stage_type = "DEPLOY_FUNCTION"
  #deployment_spec_deploy_artifact_id = <<Optional value not found in discovery>>
  description                     = ""
  display_name                    = "deploy"
  docker_image_deploy_artifact_id = oci_devops_deploy_artifact.export_project-jvm_1.id
  #failure_policy = <<Optional value not found in discovery>>
  freeform_tags = {
  }
  function_deploy_environment_id = oci_devops_deploy_environment.export_fn.id
  function_timeout_in_seconds    = "30"
  #green_backend_ips = <<Optional value not found in discovery>>
  #helm_chart_deploy_artifact_id = <<Optional value not found in discovery>>
  #helm_command_artifact_ids = <<Optional value not found in discovery>>
  #is_async = <<Optional value not found in discovery>>
  #is_debug_enabled = <<Optional value not found in discovery>>
  #is_force_enabled = <<Optional value not found in discovery>>
  #is_uninstall_on_stage_delete = <<Optional value not found in discovery>>
  #is_validation_enabled = <<Optional value not found in discovery>>
  #kubernetes_manifest_deploy_artifact_ids = <<Optional value not found in discovery>>
  #load_balancer_config = <<Optional value not found in discovery>>
  #max_history = <<Optional value not found in discovery>>
  max_memory_in_mbs = "512"
  #namespace = <<Optional value not found in discovery>>
  #oke_blue_green_deploy_stage_id = <<Optional value not found in discovery>>
  #oke_canary_deploy_stage_id = <<Optional value not found in discovery>>
  #oke_canary_traffic_shift_deploy_stage_id = <<Optional value not found in discovery>>
  #oke_cluster_deploy_environment_id = <<Optional value not found in discovery>>
  #production_load_balancer_config = <<Optional value not found in discovery>>
  #purpose = <<Optional value not found in discovery>>
  #release_name = <<Optional value not found in discovery>>
  #rollback_policy = <<Optional value not found in discovery>>
  #rollout_policy = <<Optional value not found in discovery>>
  #set_string = <<Optional value not found in discovery>>
  #set_values = <<Optional value not found in discovery>>
  #should_cleanup_on_fail = <<Optional value not found in discovery>>
  #should_not_wait = <<Optional value not found in discovery>>
  #should_reset_values = <<Optional value not found in discovery>>
  #should_reuse_values = <<Optional value not found in discovery>>
  #should_skip_crds = <<Optional value not found in discovery>>
  #should_skip_render_subchart_notes = <<Optional value not found in discovery>>
  #test_load_balancer_config = <<Optional value not found in discovery>>
  #timeout_in_seconds = <<Optional value not found in discovery>>
  #traffic_shift_target = <<Optional value not found in discovery>>
  #values_artifact_ids = <<Optional value not found in discovery>>
  #wait_criteria = <<Optional value not found in discovery>>
}

resource oci_devops_repository export_project_1 {
  default_branch = "refs/heads/main"
  
  description = ""
  freeform_tags = {
  }
  name                 = "${var.project_name}"
  parent_repository_id = ""
  project_id           = oci_devops_project.export_project.id
  repository_type      = "HOSTED"
}

#resource oci_devops_project_repository_setting export_project_project_repository_setting {
#  approval_rules {
#  }
#  merge_settings {
#    allowed_merge_strategies = [
#      "MERGE_COMMIT",
#    ]
#    default_merge_strategy = "MERGE_COMMIT"
#  }
#  project_id = oci_devops_project.export_project.id
#}

resource oci_devops_build_pipeline_stage export_deploy_2 {
  build_pipeline_id = oci_devops_build_pipeline.export_project-native_2.id
  build_pipeline_stage_predecessor_collection {
    items {
      id = oci_devops_build_pipeline_stage.export_push.id
    }
  }
  build_pipeline_stage_type = "TRIGGER_DEPLOYMENT_PIPELINE"
  #build_runner_shape_config = <<Optional value not found in discovery>>
  #build_source_collection = <<Optional value not found in discovery>>
  #build_spec_file = <<Optional value not found in discovery>>
  
  #deliver_artifact_collection = <<Optional value not found in discovery>>
  deploy_pipeline_id = oci_devops_deploy_pipeline.export_project-native.id
  description        = ""
  display_name       = "deploy"
  freeform_tags = {
  }
  #image = <<Optional value not found in discovery>>
  is_pass_all_parameters_enabled = "true"
  #primary_build_source = <<Optional value not found in discovery>>
  #private_access_config = <<Optional value not found in discovery>>
  #stage_execution_timeout_in_seconds = <<Optional value not found in discovery>>
  #wait_criteria = <<Optional value not found in discovery>>
}

resource oci_devops_build_pipeline_stage export_deploy_3 {
  build_pipeline_id = oci_devops_build_pipeline.export_project-jvm_2.id
  build_pipeline_stage_predecessor_collection {
    items {
      id = oci_devops_build_pipeline_stage.export_push_1.id
    }
  }
  build_pipeline_stage_type = "TRIGGER_DEPLOYMENT_PIPELINE"
  #build_runner_shape_config = <<Optional value not found in discovery>>
  #build_source_collection = <<Optional value not found in discovery>>
  #build_spec_file = <<Optional value not found in discovery>>
  
  #deliver_artifact_collection = <<Optional value not found in discovery>>
  deploy_pipeline_id = oci_devops_deploy_pipeline.export_project-jvm.id
  description        = ""
  display_name       = "deploy"
  freeform_tags = {
  }
  #image = <<Optional value not found in discovery>>
  is_pass_all_parameters_enabled = "true"
  #primary_build_source = <<Optional value not found in discovery>>
  #private_access_config = <<Optional value not found in discovery>>
  #stage_execution_timeout_in_seconds = <<Optional value not found in discovery>>
  #wait_criteria = <<Optional value not found in discovery>>
}

resource oci_devops_build_pipeline_stage export_push {
  build_pipeline_id = oci_devops_build_pipeline.export_project-native_2.id
  build_pipeline_stage_predecessor_collection {
    items {
      id = oci_devops_build_pipeline_stage.export_build.id
    }
  }
  build_pipeline_stage_type = "DELIVER_ARTIFACT"
  #build_runner_shape_config = <<Optional value not found in discovery>>
  #build_source_collection = <<Optional value not found in discovery>>
  #build_spec_file = <<Optional value not found in discovery>>
  
  deliver_artifact_collection {
    items {
      artifact_id   = oci_devops_deploy_artifact.export_project-native_1.id
      artifact_name = "image-native"
    }
  }
  #deploy_pipeline_id = <<Optional value not found in discovery>>
  description  = ""
  display_name = "push"
  freeform_tags = {
  }
  #image = <<Optional value not found in discovery>>
  #is_pass_all_parameters_enabled = <<Optional value not found in discovery>>
  #primary_build_source = <<Optional value not found in discovery>>
  #private_access_config = <<Optional value not found in discovery>>
  #stage_execution_timeout_in_seconds = <<Optional value not found in discovery>>
  #wait_criteria = <<Optional value not found in discovery>>
}

resource oci_devops_build_pipeline_stage export_build {
  build_pipeline_id = oci_devops_build_pipeline.export_project-native_2.id
  build_pipeline_stage_predecessor_collection {
    items {
      id = oci_devops_build_pipeline.export_project-native_2.id
    }
  }
  build_pipeline_stage_type = "BUILD"
  build_runner_shape_config {
    build_runner_type = "CUSTOM"
    memory_in_gbs     = "8"
    ocpus             = "2"
  }
  build_source_collection {
    items {
      branch = "main"
      #connection_id = <<Optional value not found in discovery>>
      connection_type = "DEVOPS_CODE_REPOSITORY"
      name            = "${var.project_name}"
      repository_id   = oci_devops_repository.export_project_1.id
      repository_url  = "https://devops.scmservice.${var.region}.oci.oraclecloud.com/namespaces/${data.oci_objectstorage_namespace.tenancy_namespace.namespace}/projects/${var.project_name}/repositories/${var.project_name}"
    }
  }
  build_spec_file = "build_spec_native.yaml"
  
  #deliver_artifact_collection = <<Optional value not found in discovery>>
  #deploy_pipeline_id = <<Optional value not found in discovery>>
  description  = ""
  display_name = "build"
  freeform_tags = {
  }
  image = "OL7_X86_64_STANDARD_10"
  #is_pass_all_parameters_enabled = <<Optional value not found in discovery>>
  primary_build_source               = "${var.project_name}"
  stage_execution_timeout_in_seconds = "36000"
  #wait_criteria = <<Optional value not found in discovery>>
}

resource oci_devops_build_pipeline_stage export_push_1 {
  build_pipeline_id = oci_devops_build_pipeline.export_project-jvm_2.id
  build_pipeline_stage_predecessor_collection {
    items {
      id = oci_devops_build_pipeline_stage.export_build_1.id
    }
  }
  build_pipeline_stage_type = "DELIVER_ARTIFACT"
  #build_runner_shape_config = <<Optional value not found in discovery>>
  #build_source_collection = <<Optional value not found in discovery>>
  #build_spec_file = <<Optional value not found in discovery>>
  
  deliver_artifact_collection {
    items {
      artifact_id   = oci_devops_deploy_artifact.export_project-jvm_1.id
      artifact_name = "image-jvm"
    }
  }
  #deploy_pipeline_id = <<Optional value not found in discovery>>
  description  = ""
  display_name = "push"
  freeform_tags = {
  }
  #image = <<Optional value not found in discovery>>
  #is_pass_all_parameters_enabled = <<Optional value not found in discovery>>
  #primary_build_source = <<Optional value not found in discovery>>
  #private_access_config = <<Optional value not found in discovery>>
  #stage_execution_timeout_in_seconds = <<Optional value not found in discovery>>
  #wait_criteria = <<Optional value not found in discovery>>
}

resource oci_devops_build_pipeline_stage export_build_1 {
  build_pipeline_id = oci_devops_build_pipeline.export_project-jvm_2.id
  build_pipeline_stage_predecessor_collection {
    items {
      id = oci_devops_build_pipeline.export_project-jvm_2.id
    }
  }
  build_pipeline_stage_type = "BUILD"
  build_runner_shape_config {
    build_runner_type = "DEFAULT"
    #memory_in_gbs = <<Optional value not found in discovery>>
    #ocpus = <<Optional value not found in discovery>>
  }
  build_source_collection {
    items {
      branch = "main"
      #connection_id = <<Optional value not found in discovery>>
      connection_type = "DEVOPS_CODE_REPOSITORY"
      name            = "${var.project_name}"
      repository_id   = oci_devops_repository.export_project_1.id
      repository_url  = "https://devops.scmservice.${var.region}.oci.oraclecloud.com/namespaces/${data.oci_objectstorage_namespace.tenancy_namespace.namespace}/projects/${var.project_name}/repositories/${var.project_name}"
    }
  }
  build_spec_file = "build_spec.yaml"
  
  #deliver_artifact_collection = <<Optional value not found in discovery>>
  #deploy_pipeline_id = <<Optional value not found in discovery>>
  description  = ""
  display_name = "build"
  freeform_tags = {
  }
  image = "OL7_X86_64_STANDARD_10"
  #is_pass_all_parameters_enabled = <<Optional value not found in discovery>>
  primary_build_source               = "${var.project_name}"
  stage_execution_timeout_in_seconds = "36000"
  #wait_criteria = <<Optional value not found in discovery>>
}

resource oci_devops_repository_ref export_project_1_repository_ref {
  commit_id = "7f9251b0eb58f0551edc8077037e12bf3b391c5d"
  #object_id = <<Optional value not found in discovery>>
  ref_name      = "main"
  ref_type      = "BRANCH"
  repository_id = oci_devops_repository.export_project_1.id
}

#resource oci_devops_repository_setting export_project_1_repository_setting {
#  approval_rules {
#  }
#  merge_checks {
#    last_build_succeeded = "DISABLED"
#  }
#  merge_settings {
#    allowed_merge_strategies = [
#      "MERGE_COMMIT",
#    ]
#    default_merge_strategy = "MERGE_COMMIT"
#  }
#  repository_id = oci_devops_repository.export_project_1.id
#}
