FROM container-registry.oracle.com/graalvm/native-image:23-ol8 AS native
WORKDIR /app

COPY target .
ADD reflection.json .

RUN native-image \
     -H:ReflectionConfigurationFiles=/app/reflection.json \
     -Ob \
     -H:Name=Hello \
     -cp "/app/Helloaifunc-1.0-SNAPSHOT.jar:/app/lib/*"  \
        com.fnproject.fn.runtime.EntryPoint

FROM fnproject/fn-java-fdk:jre17-1.0.198 as fdk

FROM container-registry.oracle.com/os/oraclelinux:8-slim
COPY --from=native /app/Hello .
COPY --from=fdk /function/runtime/* .
ENTRYPOINT [ "./Hello" ]
CMD [ "com.example.HelloAIFunction::handleRequest", "-Djava.library.path=/lib"]