create or replace FUNCTION ask_oracle_graph_sql (
    p_prompt_id IN VARCHAR2
) RETURN CLOB
AUTHID DEFINER
IS
    l_response CLOB;
    l_sql      CLOB;
    l_check    VARCHAR2(32767);
    l_cursor   INTEGER;
BEGIN
    /*
      Read the query already generated by NL2SQL or an Agent.
    */
    BEGIN
        SELECT prompt_response
          INTO l_response
          FROM user_cloud_ai_conversation_prompts
         WHERE conversation_prompt_id = p_prompt_id
         FETCH FIRST 1 ROW ONLY;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            SELECT prompt_response
              INTO l_response
              FROM adb_chat_prompts
             WHERE conversation_prompt_id = p_prompt_id
             FETCH FIRST 1 ROW ONLY;
    END;

    IF l_response IS NULL THEN
        RAISE_APPLICATION_ERROR(
            -20001,
            'No generated response was found.'
        );
    END IF;

    l_sql := TRIM(l_response);

    /* Remove Markdown SQL fences. */
    l_sql := REGEXP_REPLACE(
        l_sql,
        '^[[:space:]]*```[[:space:]]*(sql)?[[:space:]]*',
        '',
        1,
        1,
        'in'
    );

    l_sql := REGEXP_REPLACE(
        l_sql,
        '[[:space:]]*```[[:space:]]*$',
        '',
        1,
        1,
        'in'
    );

    /* Remove an OML notebook %sql prefix. */
    l_sql := REGEXP_REPLACE(
        l_sql,
        '^[[:space:]]*%sql[[:space:]]*',
        '',
        1,
        1,
        'in'
    );

    /* Remove the final semicolon. */
    l_sql := REGEXP_REPLACE(
        l_sql,
        ';[[:space:]]*$',
        ''
    );

    l_check := LOWER(
        TRIM(DBMS_LOB.SUBSTR(l_sql, 32767, 1))
    );

    /* Only read-only GRAPH_TABLE queries are allowed. */
    IF NOT REGEXP_LIKE(l_check, '^(select|with)[[:space:]]') THEN
        RAISE_APPLICATION_ERROR(
            -20002,
            'The generated response is not a read-only SQL query.'
        );
    END IF;

    IF INSTR(l_check, 'graph_table') = 0 THEN
        RAISE_APPLICATION_ERROR(
            -20003,
            'The generated response is not a GRAPH_TABLE query.'
        );
    END IF;

    IF REGEXP_LIKE(
        l_check,
        '(^|[[:space:];])(insert|update|delete|merge|drop|alter|create|truncate|grant|revoke|begin|declare|call|execute)([[:space:];]|$)'
    ) THEN
        RAISE_APPLICATION_ERROR(
            -20004,
            'Only a read-only graph query is allowed.'
        );
    END IF;

    /* Validate the query before returning it to the plugin. */
    l_cursor := DBMS_SQL.OPEN_CURSOR;

    BEGIN
        DBMS_SQL.PARSE(
            l_cursor,
            DBMS_LOB.SUBSTR(l_sql, 32767, 1),
            DBMS_SQL.NATIVE
        );

        DBMS_SQL.CLOSE_CURSOR(l_cursor);
    EXCEPTION
        WHEN OTHERS THEN
            IF DBMS_SQL.IS_OPEN(l_cursor) THEN
                DBMS_SQL.CLOSE_CURSOR(l_cursor);
            END IF;

            RAISE_APPLICATION_ERROR(
                -20005,
                'The generated graph query is invalid: ' ||
                SUBSTR(SQLERRM, 1, 1500)
            );
    END;

    RETURN l_sql;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(
            -20006,
            'No saved response exists for this prompt ID.'
        );
END ask_oracle_graph_sql;
/