{
 "title": "Triton Inference Server",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "avg queue time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(delta(nv_inference_queue_duration_us[30s])/(1+delta(nv_inference_request_success[30s])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg GPU Utilization in cluster",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(nv_gpu_utilization)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Queue Time (milliseconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Queue Time (ms)" }
   ],
   "targets": [
    {
     "expr": "rate(nv_inference_queue_duration_us[30s]) / 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cumulative Inference Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nv_inference_request_success", "legendFormat": "Success {{instance}}" },
    { "expr": "nv_inference_request_failure", "legendFormat": "Failure {{instance}}" }
   ]
  }
 ]
}