# Copyright (c) 2026 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl/.

from __future__ import annotations

import array
import os
import re
from pathlib import Path
from typing import Iterable

import oci
import oracledb
from oci.generative_ai_inference import GenerativeAiInferenceClient
from oci.generative_ai_inference.models import EmbedTextDetails, OnDemandServingMode

from workshop_helpers.oci_genai_helpers import chat_once


TABLE_NAME_RE = re.compile(r"^[A-Za-z][A-Za-z0-9_]{0,127}$")


def repo_root() -> Path:
    """Find the workshop files directory from this helper file."""
    return Path(__file__).resolve().parents[1]


def resolve_workshop_path(path_value: str) -> str:
    """Resolve .env paths from common workshop launch locations."""
    path = Path(os.path.expanduser(path_value))
    if path.is_absolute():
        return str(path.resolve())

    search_roots = [Path.cwd().resolve(), repo_root()]
    search_roots.extend(repo_root().parents)
    search_roots.extend(Path.cwd().resolve().parents)

    seen: set[Path] = set()
    for root in search_roots:
        if root in seen:
            continue
        seen.add(root)
        candidate = root / path
        if candidate.exists():
            return str(candidate.resolve())

    return str((repo_root() / path).resolve())


def resolve_tns_admin() -> str | None:
    """Return TNS_ADMIN as an absolute path and verify the wallet config exists."""
    tns_admin = os.getenv("TNS_ADMIN")
    if not tns_admin:
        return None

    resolved = resolve_workshop_path(tns_admin)
    tnsnames = Path(resolved) / "tnsnames.ora"
    if not tnsnames.is_file():
        raise FileNotFoundError(
            "TNS_ADMIN points to a directory without tnsnames.ora. "
            f"Resolved path: {resolved}. "
            "Set TNS_ADMIN to the wallet directory that contains tnsnames.ora."
        )
    return resolved


def docs_table_name() -> str:
    """Return a validated workshop table name."""
    table_name = os.getenv("DB_DOCS_TABLE", "WORKSHOP_GENAI_DOCS").upper()
    if not TABLE_NAME_RE.match(table_name):
        raise ValueError(
            "DB_DOCS_TABLE must start with a letter and contain only letters, "
            "numbers, and underscores."
        )
    return table_name


def create_db_connection() -> oracledb.Connection:
    """Connect to Oracle Database using DB_USER, DB_PASSWORD, and DB_DSN."""
    tns_admin = resolve_tns_admin()
    wallet_password = os.getenv("DB_WALLET_PASSWORD") or os.environ["DB_PASSWORD"]

    return oracledb.connect(
        user=os.environ["DB_USER"],
        password=os.environ["DB_PASSWORD"],
        dsn=os.environ["DB_DSN"],
        config_dir=tns_admin,
        wallet_location=tns_admin,
        wallet_password=wallet_password,
    )


def check_db_connection(conn: oracledb.Connection) -> dict:
    """Return a few safe connection details for notebook display."""
    sql = """
        SELECT
            SYS_CONTEXT('USERENV', 'DB_NAME') AS db_name,
            SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA') AS current_schema,
            SYS_CONTEXT('USERENV', 'SERVICE_NAME') AS service_name
        FROM dual
    """
    with conn.cursor() as cur:
        cur.execute(sql)
        row = cur.fetchone()
    return {
        "db_name": row[0],
        "current_schema": row[1],
        "service_name": row[2],
    }


def ensure_docs_table(conn: oracledb.Connection, table_name: str | None = None) -> str:
    """Create the workshop documents table if it does not already exist."""
    table_name = table_name or docs_table_name()
    ddl = f"""
        CREATE TABLE {table_name} (
            doc_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            chunk_text VARCHAR2(4000) NOT NULL,
            source VARCHAR2(255) NOT NULL,
            embedding VECTOR
        )
    """
    try:
        with conn.cursor() as cur:
            cur.execute(ddl)
        conn.commit()
    except oracledb.DatabaseError as exc:
        error = exc.args[0]
        if getattr(error, "code", None) != 955:
            raise
    return table_name


def count_documents(conn: oracledb.Connection, table_name: str | None = None) -> int:
    """Count rows in the workshop documents table."""
    table_name = table_name or docs_table_name()
    with conn.cursor() as cur:
        cur.execute(f"SELECT COUNT(*) FROM {table_name}")
        return int(cur.fetchone()[0])


def embed_texts(
    genai_client: GenerativeAiInferenceClient,
    texts: list[str],
    input_type: str,
) -> list[list[float]]:
    """Generate embeddings with the configured OCI Generative AI embedding model."""
    embed_details = EmbedTextDetails(
        inputs=texts,
        serving_mode=OnDemandServingMode(
            serving_type="ON_DEMAND",
            model_id=os.environ["EMBED_MODEL_ID"],
        ),
        compartment_id=os.environ["OCI_COMPARTMENT_ID"],
        truncate=EmbedTextDetails.TRUNCATE_END,
        input_type=input_type,
    )
    response = genai_client.embed_text(embed_details)
    payload = oci.util.to_dict(response.data)

    embeddings = payload.get("embeddings")
    if embeddings:
        return embeddings

    data = payload.get("data") or []
    embeddings = [item.get("embedding") for item in data if item.get("embedding")]
    if embeddings:
        return embeddings

    raise ValueError(f"Could not find embeddings in response: {payload}")


def embed_documents(
    genai_client: GenerativeAiInferenceClient,
    texts: list[str],
) -> list[list[float]]:
    """Embed document chunks for storage in the database."""
    return embed_texts(
        genai_client,
        texts,
        input_type=EmbedTextDetails.INPUT_TYPE_SEARCH_DOCUMENT,
    )


def embed_query(genai_client: GenerativeAiInferenceClient, question: str) -> list[float]:
    """Embed a user question for vector search."""
    return embed_texts(
        genai_client,
        [question],
        input_type=EmbedTextDetails.INPUT_TYPE_SEARCH_QUERY,
    )[0]


def vector_bind(vector: Iterable[float]) -> array.array:
    """Convert a Python list into a DB vector bind value."""
    return array.array("f", vector)


def store_embedded_documents(
    conn: oracledb.Connection,
    documents: list[dict],
    embeddings: list[list[float]],
    table_name: str | None = None,
    replace_existing: bool = True,
) -> int:
    """Insert document chunks and precomputed embeddings into Oracle Database."""
    table_name = table_name or docs_table_name()
    if len(documents) != len(embeddings):
        raise ValueError("Each document chunk must have exactly one embedding.")

    with conn.cursor() as cur:
        if replace_existing:
            cur.execute(f"DELETE FROM {table_name}")

        rows = [
            {
                "chunk_text": doc["chunk_text"],
                "source": doc["source"],
                "embedding": vector_bind(embedding),
            }
            for doc, embedding in zip(documents, embeddings, strict=True)
        ]
        if hasattr(oracledb, "DB_TYPE_VECTOR"):
            cur.setinputsizes(embedding=oracledb.DB_TYPE_VECTOR)
        cur.executemany(
            f"""
            INSERT INTO {table_name} (chunk_text, source, embedding)
            VALUES (:chunk_text, :source, :embedding)
            """,
            rows,
        )
    conn.commit()
    return len(documents)


def seed_sample_documents(
    conn: oracledb.Connection,
    genai_client: GenerativeAiInferenceClient,
    documents: list[dict],
    table_name: str | None = None,
    replace_existing: bool = True,
) -> int:
    """Embed and insert workshop sample documents."""
    table_name = table_name or docs_table_name()
    texts = [doc["chunk_text"] for doc in documents]
    embeddings = embed_documents(genai_client, texts)
    return store_embedded_documents(
        conn,
        documents,
        embeddings,
        table_name=table_name,
        replace_existing=replace_existing,
    )


def retrieve_top_k(
    conn: oracledb.Connection,
    query_vector: list[float],
    k: int = 3,
    table_name: str | None = None,
) -> list[dict]:
    """Retrieve the nearest document chunks using Oracle vector similarity search."""
    table_name = table_name or docs_table_name()
    k = max(1, min(int(k), 10))
    sql = f"""
        SELECT doc_id, chunk_text, source,
               VECTOR_DISTANCE(embedding, :qv, COSINE) AS distance
        FROM {table_name}
        ORDER BY VECTOR_DISTANCE(embedding, :qv, COSINE)
        FETCH FIRST {k} ROWS ONLY
    """
    with conn.cursor() as cur:
        if hasattr(oracledb, "DB_TYPE_VECTOR"):
            cur.setinputsizes(qv=oracledb.DB_TYPE_VECTOR)
        cur.execute(sql, qv=vector_bind(query_vector))
        return [
            {
                "doc_id": row[0],
                "chunk_text": row[1],
                "source": row[2],
                "distance": float(row[3]),
            }
            for row in cur.fetchall()
        ]


def build_grounded_prompt(question: str, rows: list[dict]) -> str:
    """Build the same grounded-answer prompt pattern used in the written guide."""
    context = "\n\n".join(
        f"[doc_id={row['doc_id']} source={row['source']}]\n{row['chunk_text']}"
        for row in rows
    )
    return f"""You are a helpful assistant. Use ONLY the context below to answer.
If the context is insufficient, say "I don't know".

Context:
{context}

Question:
{question}
"""


def chat_with_grounded_context(
    genai_client: GenerativeAiInferenceClient,
    question: str,
    rows: list[dict],
) -> str:
    """Ask the chat model to answer using only the retrieved database context."""
    prompt = build_grounded_prompt(question, rows)
    return chat_once(genai_client, prompt)
