#!/bin/bash
curl --fail -H "Authorization: Bearer Oracle" -L0 http://169.254.169.254/opc/v2/instance/metadata/oke_init_script | base64 --decode >/var/run/oke-init.sh
bash /var/run/oke-init.sh

sudo /usr/libexec/oci-growfs -y

curl https://rclone.org/install.sh | sudo bash

sudo su 

mkdir -p /opt/config/rclone

cat << EOF > /opt/config/rclone/rclone.conf
[model_bucket_oci]
type = oracleobjectstorage
provider = instance_principal_auth
namespace = ##NAMESPACE##
compartment = ##COMPARTMENT_OCID##
region = ##REGION##

EOF


#### ******* rclone service:

cat << EOF > /etc/systemd/system/rclone@.service
# User service for Rclone mounting
#
# Place in /etc/systemd/system
# File must include the '@' (ex rclone@.service)
# As your normal user, run 
#   systemctl daemon-reload
# You can now start/enable each remote by using rclone@<remote>
#   systemctl --now rclone@model_bucket_oci

# Make sure to include correct bucket name i.e:
##  %i:<bucket-name> /opt/mnt/%i

[Unit]
Description=rclone: Remote FUSE filesystem for cloud storage config %i
Documentation=man:rclone(1)
After=network-online.target
Wants=network-online.target

[Service]
Type=notify
ExecStartPre=-/usr/bin/mkdir -p /opt/mnt/%i
ExecStart= \
  /usr/bin/rclone mount \
    --config=/opt/config/rclone/rclone.conf \
    --tpslimit 50 \
    --vfs-cache-mode writes \
    --allow-non-empty \
    --transfers 10 \
    --allow-other \
    %i:NIM/llama2-7b-hf/ /opt/mnt/%i
ExecStop=/bin/fusermount -u /opt/mnt/%i

[Install]
WantedBy=default.target
EOF

systemctl daemon-reload
systemctl enable --now rclone@model_bucket_oci