CREATE TABLE "DEMO"."ACCOUNTDOCUMENT" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ACCOUNTID" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"DOCUMENTTYPE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CONFIDENCE" NUMBER(*,0), 
	"DOCUMENTNUMBER" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"FIRSTNAME" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"LASTNAME" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"COUNTRY" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"NATIONALITY" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"BIRTHDATE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"EXPIRYDATE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"GENDER" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"DOCUMENTBINARY" BLOB, 
	"DOCUMENTNAME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

CREATE UNIQUE INDEX "DEMO"."ACCOUNTDOCUMENT_PK" ON "DEMO"."ACCOUNTDOCUMENT" ("ID") 
  ;

ALTER TABLE "DEMO"."ACCOUNTDOCUMENT" MODIFY ("ID" NOT NULL ENABLE);

ALTER TABLE "DEMO"."ACCOUNTDOCUMENT" ADD CONSTRAINT "ACCOUNTDOCUMENT_PK" PRIMARY KEY ("ID")
  USING INDEX "DEMO"."ACCOUNTDOCUMENT_PK"  ENABLE;

