# This template will deploy global configurations for the entire cluster

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-config
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
    - clusters:
        selector:
          matchLabels:
            cluster: in-cluster
  template:
    metadata:
      labels:
        type: config
      name: 'cluster-config-{{ "{{" }}.name{{ "}}" }}'
    spec:
      project: {{ .Values.project }}
      sources:
        - repoURL: {{ .Values.repo }}
          targetRevision: HEAD
          path: apps/{{ "{{" }}.name{{ "}}" }}/_config_
          directory:
            recurse: true

      destination:
        server: '{{ "{{" }}.server{{ "}}" }}'
        namespace: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true