## This configuration was generated by terraform-provider-oci

resource oci_functions_application export_project_1 {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  config = {
  }
  
  display_name = "${var.project_name}"
  freeform_tags = {
  }
  network_security_group_ids = [
  ]
  shape = "GENERIC_X86"
  subnet_ids = [
    oci_core_subnet.export_project-private.id,
  ]
  syslog_url = ""
  trace_config {
    domain_id  = ""
    is_enabled = "false"
  }
}

resource oci_functions_function export_project_2 {
  application_id = oci_functions_application.export_project_1.id
  config = {
  }
  
  display_name = "${var.project_name}"
  freeform_tags = {
  }
  image         = "${var.registry}/${data.oci_objectstorage_namespace.tenancy_namespace.namespace}/${var.image_name}:1"
  #image_digest  = 
  memory_in_mbs = "512"
  provisioned_concurrency_config {
    #count = <<Optional value not found in discovery>>
    strategy = "NONE"
  }
  timeout_in_seconds = "30"
  trace_config {
    is_enabled = "false"
  }
  depends_on = [oci_artifacts_container_repository.export_project]
}
