apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resourceset.yml

configMapGenerator:
  - name: kube-prometheus-stack-values
    namespace: flux-system
    files:
      - 00-base.yaml=values/00-base.yml
      - 90-overrides.yaml=values/90-overrides.yml

generatorOptions:
  disableNameSuffixHash: true
