server.port=8080
server.host=0.0.0.0

data.persistence-units.jakarta.0.connection.username=${javax.sql.DataSource.credit.user:sa}
data.persistence-units.jakarta.0.connection.password=${javax.sql.DataSource.credit.password:}
data.persistence-units.jakarta.0.connection.url=${javax.sql.DataSource.credit.URL:jdbc:h2:mem:credit;MODE=Oracle;DB_CLOSE_DELAY=-1}
data.persistence-units.jakarta.0.connection.jdbc-driver-class-name=${javax.sql.DataSource.credit.driver:org.h2.Driver}
data.persistence-units.jakarta.0.properties.eclipselink.target-database=${eclipselink.target-database:Oracle}
data.persistence-units.jakarta.0.properties.eclipselink.target-server=None
data.persistence-units.jakarta.0.properties.jakarta.persistence.schema-generation.database.action=none
