apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-restricted-binding
  namespace: example
subjects:
  - kind: ServiceAccount
    name: application-sa
    namespace: example
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-restricted