version: 0.1
component: build
timeoutInSeconds: 10000
runAs: root
shell: bash

env:
  variables:
    repo_compartment_id: ""
    repo_prefix: ""
    region: ""
    region_key: ""
    images_to_mirror: ""
    tenancy_namespace: ""

steps:

  - type: Command
    name: "Load variables"
    failImmediatelyOnError: true
    command: |
      source ./variables.sh
      # Export other variables here to override them
      # export region="eu-frankfurt-1"
      export OCI_CLI_REGION=${region}
      region_key=$(oci iam region list --query "data[?name == '$region'].key | [0]" --raw-output);
      export region_key=$(echo "$region_key" | tr '[:upper:]' '[:lower:]');
      export tenancy_namespace=$(oci artifacts container configuration get --compartment-id "${repo_compartment_id}" --query data.namespace --raw-output);
    onFailure:
      - type: Command
        command: |
          echo "Error loading common environment variables";
        timeoutInSeconds: 400

  - type: Command
    timeoutInSeconds: 600
    name: "Mirror Images"
    failImmediatelyOnError: true
    command: |
      export OCI_CLI_REGION=${region}
      ./script/mirror-image.sh -c "${repo_compartment_id}" -k "${region_key}" -p "${repo_prefix}" -i "${images_to_mirror}" -t "${tenancy_namespace}"
    onFailure:
      - type: Command
        command: |
          echo "Failed to mirror images to OCIR!";
        timeoutInSeconds: 400
