resources:
- bases/functions.oci.oracle.com_functionapplications.yaml
- bases/functions.oci.oracle.com_functions.yaml
- bases/functions.oci.oracle.com_functionjobs.yaml
- bases/functions.oci.oracle.com_functionevents.yaml
- bases/functions.oci.oracle.com_functioneventtriggers.yaml
