apiVersion: v1
kind: Service
metadata:
  name: api-{{ .Values.global.environment }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .Values.global.application | quote }}
    app.kubernetes.io/component: api
    app.kubernetes.io/environment: {{ .Values.global.environment | quote }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
