
set define off

prompt Creating Data Product Governance sample schema...

begin execute immediate 'drop table dpg_audit_events purge'; exception when others then if sqlcode != -942 then raise; end if; end;
/
begin execute immediate 'drop table dpg_tasks purge'; exception when others then if sqlcode != -942 then raise; end if; end;
/
begin execute immediate 'drop table dpg_approvals purge'; exception when others then if sqlcode != -942 then raise; end if; end;
/
begin execute immediate 'drop table dpg_quality_issues purge'; exception when others then if sqlcode != -942 then raise; end if; end;
/
begin execute immediate 'drop table dpg_access_requests purge'; exception when others then if sqlcode != -942 then raise; end if; end;
/
begin execute immediate 'drop table dpg_product_datasets purge'; exception when others then if sqlcode != -942 then raise; end if; end;
/
begin execute immediate 'drop table dpg_product_requests purge'; exception when others then if sqlcode != -942 then raise; end if; end;
/
begin execute immediate 'drop table dpg_datasets purge'; exception when others then if sqlcode != -942 then raise; end if; end;
/
begin execute immediate 'drop table dpg_data_products purge'; exception when others then if sqlcode != -942 then raise; end if; end;
/

create table dpg_data_products (
    product_id           number generated by default on null as identity primary key,
    product_name         varchar2(200) not null,
    business_domain      varchar2(100) not null,
    business_owner       varchar2(150) not null,
    status               varchar2(30) default 'Draft' not null,
    priority             varchar2(20) default 'Medium' not null,
    requested_by         varchar2(150),
    requested_on         date default sysdate not null,
    target_delivery_date date,
    description          clob
);

create table dpg_datasets (
    dataset_id        number generated by default on null as identity primary key,
    dataset_name      varchar2(200) not null,
    source_system     varchar2(120),
    business_domain   varchar2(100),
    classification    varchar2(40) default 'Internal' not null,
    steward_name      varchar2(150),
    refresh_frequency varchar2(40),
    status            varchar2(30) default 'Active' not null,
    description       clob
);

create table dpg_product_requests (
    request_id      number generated by default on null as identity primary key,
    product_id      number,
    request_title   varchar2(200) not null,
    requester_name  varchar2(150) not null,
    business_unit   varchar2(120),
    request_type    varchar2(40) default 'New Product' not null,
    status          varchar2(30) default 'Submitted' not null,
    priority        varchar2(20) default 'Medium' not null,
    submitted_on    date default sysdate not null,
    due_date        date,
    justification   clob,
    constraint dpg_pr_product_fk foreign key (product_id)
        references dpg_data_products (product_id)
);

create table dpg_product_datasets (
    product_id number not null,
    dataset_id number not null,
    usage_note varchar2(500),
    constraint dpg_pd_pk primary key (product_id, dataset_id),
    constraint dpg_pd_product_fk foreign key (product_id)
        references dpg_data_products (product_id),
    constraint dpg_pd_dataset_fk foreign key (dataset_id)
        references dpg_datasets (dataset_id)
);

create table dpg_access_requests (
    access_request_id number generated by default on null as identity primary key,
    dataset_id         number not null,
    requester_name     varchar2(150) not null,
    access_purpose     varchar2(500) not null,
    access_level       varchar2(40) default 'Read' not null,
    status             varchar2(30) default 'Submitted' not null,
    requested_on       date default sysdate not null,
    approved_by        varchar2(150),
    decision_on        date,
    constraint dpg_ar_dataset_fk foreign key (dataset_id)
        references dpg_datasets (dataset_id)
);

create table dpg_quality_issues (
    issue_id         number generated by default on null as identity primary key,
    dataset_id       number not null,
    issue_title      varchar2(200) not null,
    severity         varchar2(20) default 'Medium' not null,
    status           varchar2(30) default 'Open' not null,
    reported_by      varchar2(150) not null,
    reported_on      date default sysdate not null,
    assigned_to      varchar2(150),
    resolution_notes clob,
    constraint dpg_qi_dataset_fk foreign key (dataset_id)
        references dpg_datasets (dataset_id)
);

create table dpg_approvals (
    approval_id   number generated by default on null as identity primary key,
    request_type  varchar2(40) not null,
    request_id    number not null,
    approver_name varchar2(150) not null,
    decision      varchar2(30) default 'Pending' not null,
    decision_date date,
    comments      varchar2(1000)
);

create table dpg_tasks (
    task_id      number generated by default on null as identity primary key,
    related_type varchar2(40) not null,
    related_id   number not null,
    task_name    varchar2(200) not null,
    assigned_to  varchar2(150),
    status       varchar2(30) default 'Open' not null,
    due_date     date
);

create table dpg_audit_events (
    audit_id    number generated by default on null as identity primary key,
    event_type  varchar2(60) not null,
    entity_name varchar2(60) not null,
    entity_id   number,
    event_by    varchar2(150),
    event_on    date default sysdate not null,
    event_note  varchar2(1000)
);

create index dpg_pr_status_idx on dpg_product_requests (status);
create index dpg_ar_status_idx on dpg_access_requests (status);
create index dpg_qi_status_idx on dpg_quality_issues (status);
create index dpg_tasks_status_idx on dpg_tasks (status);

comment on table dpg_data_products is 'Business-facing data products requested, governed, delivered, and tracked by the organization.';
comment on table dpg_datasets is 'Catalog of datasets that may support data products, access requests, and data quality tracking.';
comment on table dpg_product_requests is 'Requests to create, enhance, or retire data products.';
comment on table dpg_product_datasets is 'Relationship between data products and the datasets they use.';
comment on table dpg_access_requests is 'Requests from users who need access to governed datasets.';
comment on table dpg_quality_issues is 'Data quality issues reported against cataloged datasets.';
comment on table dpg_approvals is 'Approval decisions for product, access, and governance requests.';
comment on table dpg_tasks is 'Work items used to deliver requests, resolve issues, and complete governance actions.';
comment on table dpg_audit_events is 'Traceable history of important user and system events.';

comment on column dpg_data_products.status is 'Lifecycle status such as Draft, Under Review, Approved, In Development, Published, or Retired.';
comment on column dpg_datasets.classification is 'Data sensitivity classification such as Public, Internal, Confidential, or Restricted.';
comment on column dpg_product_requests.request_type is 'Type of request such as New Product, Enhancement, Change, or Retirement.';
comment on column dpg_access_requests.access_level is 'Requested access level such as Read, Export, Steward, or Admin.';
comment on column dpg_quality_issues.severity is 'Business impact of the quality issue such as Low, Medium, High, or Critical.';
comment on column dpg_approvals.decision is 'Approval outcome such as Pending, Approved, Rejected, or More Information Needed.';

insert into dpg_data_products (
    product_name, business_domain, business_owner, status, priority, requested_by, target_delivery_date, description
) values (
    'Customer 360 Data Product', 'Customer', 'Aisha Khan', 'In Development', 'High', 'Omar Saleh', sysdate + 30,
    'Unified customer profile for analytics, segmentation, and service insights.'
);

insert into dpg_data_products (
    product_name, business_domain, business_owner, status, priority, requested_by, target_delivery_date, description
) values (
    'Finance KPI Data Product', 'Finance', 'Maya Haddad', 'Approved', 'Medium', 'Lina Nasser', sysdate + 45,
    'Curated finance metrics for revenue, cost, margin, and management reporting.'
);

insert into dpg_datasets (
    dataset_name, source_system, business_domain, classification, steward_name, refresh_frequency, status, description
) values (
    'Customer Master', 'CRM', 'Customer', 'Confidential', 'Nora Ali', 'Daily', 'Active',
    'Golden customer records, identifiers, and account attributes.'
);

insert into dpg_datasets (
    dataset_name, source_system, business_domain, classification, steward_name, refresh_frequency, status, description
) values (
    'Invoice Transactions', 'ERP', 'Finance', 'Restricted', 'Fahad Omar', 'Hourly', 'Active',
    'Invoice-level finance transactions used for reporting and reconciliation.'
);

insert into dpg_product_requests (
    product_id, request_title, requester_name, business_unit, request_type, status, priority, due_date, justification
) values (
    1, 'Add customer consent indicators', 'Omar Saleh', 'Marketing', 'Enhancement', 'Submitted', 'High', sysdate + 14,
    'Marketing users need consent visibility before campaign activation.'
);

insert into dpg_access_requests (
    dataset_id, requester_name, access_purpose, access_level, status
) values (
    1, 'Sara Ahmed', 'Analyze customer churn trends for retention planning.', 'Read', 'Submitted'
);

insert into dpg_quality_issues (
    dataset_id, issue_title, severity, status, reported_by, assigned_to
) values (
    2, 'Missing tax amount on recent invoices', 'High', 'Open', 'Yousef Malik', 'Fahad Omar'
);

insert into dpg_approvals (
    request_type, request_id, approver_name, decision, comments
) values (
    'Access Request', 1, 'Nora Ali', 'Pending', 'Awaiting steward review.'
);

insert into dpg_tasks (
    related_type, related_id, task_name, assigned_to, status, due_date
) values (
    'Quality Issue', 1, 'Investigate missing tax amount records', 'Fahad Omar', 'Open', sysdate + 7
);

insert into dpg_audit_events (
    event_type, entity_name, entity_id, event_by, event_note
) values (
    'Created', 'DATA_PRODUCT', 1, 'System', 'Sample data product created during installation.'
);

commit;

prompt Data Product Governance sample schema installed.