apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - applications/reference-app/infrastructure/resourceset.yml
  - applications/reference-app/components/resourceset.yml
  - applications/reference-helm-app/infrastructure/resourceset.yml
  - applications/reference-helm-app/components/resourceset.yml
