export const APP_CONFIG = {
  availableColors: [
    "#2E2E2E",
    "#2979FF",
    "#34C759",
    "#FF9500",
    "#FF375F",
    "#AF52DE",
    "#8E8E93",
    "#FFD60A",
  ],
  availableImages: [
    "/background.png",
    "/backgrounds/radial-sky-blue.jpg",
    "/backgrounds/sonoma.jpg",
    "/backgrounds/imac-blue.jpg",
    "/backgrounds/imac-green.jpg",
    "/backgrounds/imac-orange.jpg",
    "/backgrounds/imac-pink.jpg",
    "/backgrounds/imac-purple.jpg",
    "/backgrounds/imac-silver.jpg",
    "/backgrounds/imac-yellow.jpg",
  ],
  defaults: {
    color: "#3a3632",
    image: "/backgrounds/imac-blue.jpg",
    backgroundColor: "#F5F5F5",
    name: "OCI Generative AI Agents",
    logoUrl: "",
    speechProvider: "browser",
  },
};
