# Deploy all helm application on all qa clusters.

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-apps-qa
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
    - matrix:
        generators:
          - git:
              repoURL: {{ .Values.repo }}
              revision: HEAD
              directories:
                - path: apps/helm/charts/*
          - clusters:
              selector:
                matchLabels:
                  type: "workload"
                matchExpressions:
                  - key: "qa"
                    operator: In
                    values:
                      - "true"

  syncPolicy:
    preserveResourcesOnDeletion: false     # If true, application will be kept even if removed from ArgoCD
  template:
    metadata:
      name: '{{ "{{" }}index .path.segments 3{{ "}}" }}-{{ "{{" }}.nameNormalized{{ "}}" }}-qa'
    spec:
      project: team-project    # Project dedicated to this development team
      sources:
        - repoURL: {{ .Values.repo }}
          path: '{{ "{{" }}.path.path{{ "}}" }}'
          targetRevision: HEAD       # Git HEAD will represent the latest state of the applications
          helm:
            releaseName: '{{ "{{" }}index .path.segments 3{{ "}}" }}-qa'
            valueFiles:
              - $values/apps/helm/values/{{ "{{" }}index .path.segments 3{{ "}}" }}/values-common.yml
              - $values/apps/helm/values/{{ "{{" }}index .path.segments 3{{ "}}" }}/env-type/values-no-prod.yml
              # If you have some image tag version that differ between environments
              - $values/apps/helm/values/{{ "{{" }}index .path.segments 3{{ "}}" }}/version/values-qa.yml
              # Environment specific configurations
              - $values/apps/helm/values/{{ "{{" }}index .path.segments 3{{ "}}" }}/envs/values-qa.yml


        - repoURL: {{ .Values.repo }}
          targetRevision: HEAD
          ref: values
      destination:
        server: '{{ "{{" }}.server{{ "}}" }}'
        namespace: 'namespace-qa'       # This is just the default qa namespace. If an application needs to be deployed on another namespace, it must be set in the helm values
      syncPolicy:
        syncOptions:
          - CreateNamespace=false       # qa namespace should already have been created
          - ServerSideApply=true
        automated:
          prune: true
          selfHeal: true