apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: oci-vault
spec:
  provider:
    oracle:
      vault: ocid1.vault.oc1.<region>.<vault-ocid>
      region: <region>
      principalType: Workload
