# Insert Git repository where the cluster configurations are located, with .git postfix. This template has to be applied manually

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-cluster-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ${REPO}
    targetRevision: HEAD
    path: appsets
    helm:
      parameters:
        - name: repo
          value: ${REPO}
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: true