apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secret
  namespace: <your-namespace>  # usually matches the app name
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: oci-vault
    kind: SecretStore
  target:
    name: app-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: <app>-<env>