"""IAM policy generation for Database Management and Ops Insights enablement."""

from __future__ import annotations

from dbman_opsi.config import EnablementConfig


def policy_statements(config: EnablementConfig) -> tuple[str, ...]:
    """Return least-practical PoC policy statements for the selected compartment."""

    group = config.policy_group_name
    location = f"compartment id {config.compartment_id}" if config.compartment_id else "tenancy"
    return (
        f"Allow group {group} to manage database-family in {location}",
        f"Allow group {group} to manage database-management-family in {location}",
        f"Allow group {group} to manage opsi-family in {location}",
        f"Allow group {group} to manage management-agents in {location}",
        f"Allow group {group} to manage vaults in {location}",
        f"Allow group {group} to manage keys in {location}",
        f"Allow group {group} to manage secret-family in {location}",
        f"Allow group {group} to use virtual-network-family in {location}",
        f"Allow group {group} to read metrics in {location}",
        # Service principals required for PE-based Database Management and Ops
        # Insights with Vault credentials. DB Management uses the `dpd` principal
        # (there is no `database-management` service principal).
        f"Allow service dpd to read secret-family in {location}",
        f"Allow service dpd to use virtual-network-family in {location}",
        f"Allow service operations-insights to read secret-family in {location}",
        f"Allow service operations-insights to use virtual-network-family in {location}",
    )


def terraform_policy_documents(config: EnablementConfig) -> dict[str, object]:
    return {
        "policy_name": "dbman-opsi-enable-policy",
        "policy_description": "Database Management and Ops Insights enablement policy generated by dbman-opsi.",
        "policy_statements": list(policy_statements(config)),
    }

