apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: {{ .Values.namespace }}
  labels:
    app: backend
    {{- include "enterprise-chat-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.backend.type }}
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: {{ .Values.namespace }}
  labels:
    app: frontend
    {{- include "enterprise-chat-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.frontend.type }}
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.frontend.port }}
