apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      reconcile.fluxcd.io/watch: Enabled

configMapGenerator:
  - name: flux-operator-values
    namespace: flux-system
    files:
      - 00-bootstrap.yaml=values/00-bootstrap.yml
      - 90-user.yaml=values/90-user.yml

generatorOptions:
  disableNameSuffixHash: true

resources:
  - resourceset.yml
