"""Static log-source/parser/field definitions (SOC Application + Octo APM source/parser/field definitions).

Auto-extracted from setup_log_sources.py (behavior-preserving). Pure data — no
logic, no OCI calls.
"""


APP_PARSER_NAME = "socApplicationJsonParser"
APP_PARSER_DISPLAY = "SOC Application JSON Parser"
APP_PARSER_DESC = (
    "Parses application and browser telemetry JSON for the Application 360 and "
    "browser attack dashboards. Maps service name, request metadata, trace IDs, "
    "security attack context, and browser span attributes."
)
APP_FIELD_MAPPINGS = [
    ("msg",                  "$.message",            1),
    ("time",                 "$.timestamp",          2),
    ("Service Name",         "$.serviceName",        3),
    ("Application Name",     "$.serviceName",        4),
    ("Trace ID",             "$.traceId",            5),
    ("HTTP Method",          "$.httpMethod",         6),
    ("Request URL",          "$.requestUrl",         7),
    ("URI Path",             "$.uriPath",            8),
    ("Query String",         "$.queryString",        9),
    ("Response Code",        "$.statusCode",        10),
    ("Response Time Ms",     "$.responseTimeMs",    11),
    ("Client IP",            "$.clientAddress",     12),
    ("User Agent",           "$.userAgent",         13),
    ("User",                 "$.user",              14),
    ("Session ID",           "$.sessionId",         15),
    ("Request ID",           "$.requestId",         16),
    ("Content Type",         "$.contentType",       17),
    ("Referrer",             "$.referrer",          18),
    ("Response Headers",     "$.responseHeaders",   19),
    ("Span Name",            "$.spanName",          20),
    ("Span Attributes",      "$.spanAttributes",    21),
    ("Span ID",              "$.spanId",            22),
    ("Parent Span ID",       "$.parentSpanId",      23),
    ("Span Kind",            "$.spanKind",          24),
    ("APM Domain",           "$.apmDomain",         25),
    ("Metric Name",          "$.metricName",        26),
    ("Metric Value",         "$.metricValue",       27),
    ("Metric Unit",          "$.metricUnit",        28),
    ("Attack Type",          "$.securityAttackType", 29),
    ("Risk Level",           "$.securityAttackSeverity", 30),
    ("WAF Score",            "$.wafScore",          31),
    ("DB Target",            "$.dbTarget",          32),
    ("Error Type",           "$.errorType",         33),
    ("Slow Request",         "$.slowRequest",       34),
    ("Orders Sync Created",  "$.ordersSyncCreated", 35),
    ("Orders Sync Updated",  "$.ordersSyncUpdated", 36),
    ("Orders Sync Failed",   "$.ordersSyncFailed",  37),
    ("Orders Sync Source",   "$.ordersSyncSource",  38),
    ("Severity Level",       "$.level",             39),
    ("Host Name",            "$.hostname",          40),
    # Octo APM Demo / OTel-style structured logs. These duplicate some
    # display fields intentionally so existing synthetic logs and real app
    # logs resolve to the same dashboard-facing field names.
    ("Service Name",         "$.service.name",      41),
    ("Service Namespace",    "$.service.namespace", 42),
    ("Service Version",      "$.service.version",   43),
    ("Service Instance ID",  "$.service.instance.id", 44),
    ("Deployment Environment", "$.deployment.environment", 45),
    ("Application Name",     "$.app.name",          46),
    ("App Name",             "$.app.name",          47),
    ("App Brand",            "$.app.brand",         48),
    ("App Runtime",          "$.app.runtime",       49),
    ("App Service",          "$.app.service",       50),
    ("Trace ID",             "$.trace_id",          51),
    ("Trace ID",             "$.oracleApmTraceId",  52),
    ("Span ID",              "$.span_id",           53),
    ("Span ID",              "$.oracleApmSpanId",   54),
    ("Trace Parent",         "$.traceparent",       55),
    ("HTTP Method",          "$.http.method",       56),
    ("HTTP Method",          "$.http.request.method", 57),
    ("Request URL",          "$.http.url.path",     58),
    ("URI Path",             "$.http.url.path",     59),
    ("URL Path",             "$.http.url.path",     60),
    ("Response Code",        "$.http.status_code",  61),
    ("Response Code",        "$.http.response.status_code", 62),
    ("HTTP Status Code",     "$.http.status_code",  63),
    ("HTTP Status Code",     "$.http.response.status_code", 64),
    ("Response Time Ms",     "$.http.response_time_ms", 65),
    ("Client IP",            "$.http.client_ip",    66),
    ("Client IP",            "$.client.address",    67),
    ("User Agent",           "$.user_agent.original", 68),
    ("User Agent",           "$.http.user_agent",   69),
    ("Request ID",           "$.request_id",        70),
    ("Workflow ID",          "$.workflow_id",       71),
    ("Workflow Step",        "$.workflow_step",     72),
    ("Correlation ID",       "$.correlation.id",    73),
    ("Run ID",               "$.run_id",            74),
    ("DB Target",            "$.db.target",         75),
    ("DB Statement",         "$.db.statement",      76),
    ("DB Elapsed ms",        "$.db.elapsed_ms",     77),
    ("DB Connection Name",   "$.db.connection_name", 78),
    ("DB OCID",              "$.db.ocid",           79),
    ("Slow Request",         "$.performance.slow_request", 80),
    ("Host Name",            "$.host.name",         81),
    ("Java APM Path",        "$.java_apm.path",     82),
    ("Java APM Status Code", "$.java_apm.status_code", 83),
    ("Java APM Latency ms",  "$.java_apm.latency_ms", 84),
    ("Java APM Error Type",  "$.java_apm.error_type", 85),
    ("Attack ID",           "$.security.attack.id", 86),
    ("Attack Stage",        "$.security.attack.stage", 87),
    ("Attack Type",         "$.security.attack.type", 88),
    ("Attack Entry Point",  "$.attack.entry_point", 89),
    ("Attack Payload",      "$.security.attack.payload", 90),
    ("LOTL Binary",         "$.attack.lotl_binary", 91),
    ("Security Severity",   "$.security.severity", 92),
    ("MITRE Tactic",        "$.mitre.tactic", 93),
    ("MITRE Technique ID",  "$.mitre.technique_id", 94),
    ("MITRE Technique",     "$.mitre.technique", 95),
    ("Source IP",           "$.source.ip", 96),
    ("Server Address",      "$.server.address", 97),
    ("Destination IP",      "$.destination.ip", 98),
    ("Destination Port",    "$.destination.port", 99),
    ("Network Protocol",    "$.network.protocol.name", 100),
    ("OSQuery Query",       "$.osquery.query", 101),
    ("OSQuery Finding",     "$.osquery.finding", 102),
    ("OSQuery SQL",         "$.osquery.sql", 103),
    ("OSQuery Result Count", "$.osquery.result_count", 104),
    ("Instance OCID",       "$.cloud.instance.id", 105),
    ("Host Role",           "$.host.role", 106),
    ("Compromised VM",      "$.vm.compromised", 107),
    ("Process Name",        "$.process.name", 108),
    ("Process Command Line", "$.process.command_line", 109),
    ("File Path",           "$.file.path", 110),
    ("Payment Provider",    "$.payment.provider", 111),
    ("Payment Status",      "$.payment.status", 112),
    ("Payment Risk Score",  "$.payment.risk_score", 113),
    ("Payment Network",     "$.payment.card_brand", 114),
    ("Payment Card Last4",  "$.payment.card_last4", 115),
    ("Payment Interception", "$.payment.interception.detected", 116),
    ("Payment Redirect",    "$.payment.redirect.detected", 117),
    ("Payment Redirect URL", "$.payment.redirect.url", 118),
    ("HTTP Redirect Location", "$.http.redirect.location", 119),
    ("Network Bytes Out",   "$.network.bytes_out", 120),
    ("WAF Action",          "$.wafAction", 121),
    ("WAF Action",          "$.waf.action", 122),
    ("Severity",            "$.level", 123),
    ("Severity",            "$.severity", 124),
    # Keep $.message on the built-in msg field only. Mapping it to
    # "Original Log Content" resolves to reserved field mbody and OCI rejects
    # that mapping for custom parsers.
    ("Service",             "$.service.name", 125),
    ("Service",             "$.serviceName", 126),
    ("HTTP Request Method", "$.http.request.method", 127),
    ("HTTP Request Method", "$.http.method", 128),
    ("User ID (hashed)",    "$.user_id_hash", 129),
    ("Business ID",         "$.business_id", 130),
    ("API Gateway Name",    "$.oci.api_gateway.name", 131),
    ("API Gateway Scope",   "$.oci.api_gateway.scope", 132),
    ("API Gateway Deployment ID", "$.oci.api_gateway.deployment_id", 133),
    ("API Gateway Route",   "$.oci.api_gateway.route", 134),
    ("API Gateway Route ID", "$.oci.api_gateway.route_id", 135),
    ("API Gateway Route Family", "$.oci.api_gateway.route_family", 136),
    ("API Gateway Request ID", "$.oci.api_gateway.request_id", 137),
    ("API Gateway Action",  "$.oci.api_gateway.action", 138),
    ("API Gateway Policy Decision", "$.oci.api_gateway.policy.decision", 139),
    ("API Gateway Latency ms", "$.oci.api_gateway.latency_ms", 140),
    ("API Gateway Rate Limit", "$.oci.api_gateway.rate_limit.limit", 141),
    ("API Gateway Rate Remaining", "$.oci.api_gateway.rate_limit.remaining", 142),
    ("API Gateway Threat Signal", "$.oci.api_gateway.threat_signal", 143),
    ("Chaos Injected",      "$.chaos.injected", 144),
    ("Chaos Scenario",      "$.chaos.scenario", 145),
    ("Chaos TTL Seconds",   "$.chaos.ttl_seconds", 146),
    ("Chaos Target",        "$.chaos.target", 147),
    # OKE app stdout and Java gateway records use both OTel semantic keys and
    # Log Analytics-friendly aliases. Map both into the reusable SOC fields.
    ("Service Name",         "$.service_name", 148),
    ("Service Namespace",    "$.service_namespace", 149),
    ("Service Instance ID",  "$.service_instance_id", 150),
    ("Deployment Environment", "$.deployment_environment", 151),
    ("Trace ID",             "$.traceId", 152),
    ("Span ID",              "$.spanId", 153),
    ("Request ID",           "$.request_id", 154),
    ("URL Path",             "$.url_path", 155),
    ("HTTP Status Code",     "$.http_status_code", 156),
    ("Order ID",             "$.orders.order_id", 157),
    ("Order ID",             "$.orders.id", 158),
    ("Order ID",             "$.order_id", 159),
    ("Source Order ID",      "$.source_order_id", 160),
    ("Payment Gateway Request ID", "$.payment.gateway.request_id", 161),
    ("Payment Gateway Request ID", "$.payment_gateway_request_id", 162),
    ("Payment Provider",     "$.payment.provider", 163),
    ("Payment Provider",     "$.payment_provider", 164),
    ("Payment Status",       "$.payment.status", 165),
    ("Payment Status",       "$.payment_status", 166),
    ("Payment Network",      "$.payment.network", 167),
    ("Payment Network",      "$.payment_network", 168),
    ("Payment Wallet Token Hash", "$.payment.wallet_token_hash", 169),
    ("Payment Wallet Token Hash", "$.payment.wallet.token_hash", 170),
    ("Payment Wallet Token Hash", "$.payment_wallet_token_hash", 171),
    ("Payment Risk Score",   "$.payment.risk_score", 172),
    ("Payment Risk Score",   "$.payment_risk_score", 173),
    ("Payment Network",      "$.payment.card_brand", 174),
    ("Payment Network",      "$.payment.card.brand", 175),
    ("Payment Card Last4",   "$.payment.card_last4", 176),
    ("Payment Card Last4",   "$.payment.card.last4", 177),
    ("Gateway",              "$.payment.gateway.name", 178),
    ("Gateway",              "$.payment_gateway_name", 179),
    ("Provider",             "$.payment.gateway.provider", 180),
    ("Provider",             "$.payment_gateway_provider", 181),
    ("Version",              "$.payment.gateway.version", 182),
    ("Version",              "$.payment_gateway_version", 183),
    ("Step Id",              "$.payment.gateway.step", 184),
    ("Step Id",              "$.payment_gateway_step", 185),
    ("Process Phase",        "$.payment.gateway.phase", 186),
    ("Process Phase",        "$.payment_gateway_phase", 187),
    ("Event Status",         "$.payment.gateway.step_status", 188),
    ("Event Status",         "$.payment_gateway_step_status", 189),
    ("Elapsed Time (Gateway)", "$.payment.gateway.step_latency_ms", 190),
    ("Elapsed Time (Gateway)", "$.payment_gateway_step_latency_ms", 191),
    ("Request Type",         "$.payment.gateway.request_shape", 192),
    ("Authorization Scheme", "$.payment.gateway.authorization_type", 193),
    ("Method",               "$.payment.method", 194),
    ("Method",               "$.payment_method", 195),
    ("ORDER_AMOUNT",         "$.payment.amount_minor_units", 196),
    ("ORDER_AMOUNT",         "$.payment_amount_minor_units", 197),
    ("BillingCurrency",      "$.payment.currency", 198),
    ("BillingCurrency",      "$.payment_currency", 199),
    ("Response Code",        "$.payment.processor.response_code", 200),
    ("Response Code",        "$.payment_processor_response_code", 201),
    ("Gateway ID",           "$.payment.processor.gateway_code", 202),
    ("Gateway ID",           "$.payment_processor_gateway_code", 203),
    ("Transaction ID",       "$.payment.network.transaction_id", 204),
    ("Transaction ID",       "$.payment_network_transaction_id", 205),
    ("Result",               "$.payment.card.avs.result", 206),
    ("Result",               "$.payment_card_avs_result", 207),
    ("Security Result",      "$.payment.card.cvv.result", 208),
    ("Security Result",      "$.payment_card_cvv_result", 209),
    ("Program",              "$.payment.3ds.program", 210),
    ("Program",              "$.payment_3ds_program", 211),
    ("Flow Code",            "$.payment.3ds.eci", 212),
    ("Flow Code",            "$.payment_3ds_eci", 213),
    ("Flow",                 "$.payment.3ds.flow", 214),
    ("Flow",                 "$.payment_3ds_flow", 215),
    ("Java APM Path",        "$.java_apm_path", 216),
    ("Java APM Status Code", "$.java_apm_status_code", 217),
    ("Java APM Latency ms",  "$.java_apm_latency_ms", 218),
    ("Java APM Error Type",  "$.java_apm_error_type", 219),
    ("Downstream Component", "$.java_apm.service.name", 220),
    ("Downstream Component", "$.payment.processor.name", 221),
    ("Downstream Component", "$.java_apm_service_name", 222),
    ("Downstream Component", "$.payment_processor_name", 223),
]
OCTO_APM_FIELD_DISPLAY_NAMES = (
    "Service",
    "Severity",
    "APM Domain",
    "Service Namespace",
    "Service Version",
    "Service Instance ID",
    "Deployment Environment",
    "App Name",
    "App Brand",
    "App Runtime",
    "App Service",
    "Trace ID",
    "Trace Parent",
    "Span ID",
    "Parent Span ID",
    "Span Name",
    "Span Attributes",
    "Span Kind",
    "Workflow ID",
    "Workflow Step",
    "Correlation ID",
    "Run ID",
    "Request ID",
    "URL Path",
    "HTTP Status Code",
    "HTTP Request Method",
    "Response Time Ms",
    "Metric Name",
    "Metric Value",
    "Metric Unit",
    "DB Target",
    "DB Statement",
    "DB Elapsed ms",
    "DB Connection Name",
    "DB OCID",
    "Error Type",
    "Slow Request",
    "Java APM Path",
    "Java APM Status Code",
    "Java APM Latency ms",
    "Java APM Error Type",
    "Attack ID",
    "Attack Stage",
    "Attack Type",
    "Attack Entry Point",
    "Attack Payload",
    "LOTL Binary",
    "Security Severity",
    "MITRE Tactic",
    "MITRE Technique ID",
    "MITRE Technique",
    "Source IP",
    "Server Address",
    "Destination IP",
    "Destination Port",
    "Network Protocol",
    "OSQuery Query",
    "OSQuery Finding",
    "OSQuery SQL",
    "OSQuery Result Count",
    "Instance OCID",
    "Host Role",
    "Compromised VM",
    "Process Name",
    "Process Command Line",
    "File Path",
    "Payment Provider",
    "Payment Status",
    "Payment Risk Score",
    "Payment Card Last4",
    "Payment Interception",
    "Payment Redirect",
    "Payment Redirect URL",
    "HTTP Redirect Location",
    "Network Bytes Out",
    "User ID (hashed)",
    "Business ID",
    "API Gateway Name",
    "API Gateway Scope",
    "API Gateway Deployment ID",
    "API Gateway Route",
    "API Gateway Route ID",
    "API Gateway Route Family",
    "API Gateway Request ID",
    "API Gateway Action",
    "API Gateway Policy Decision",
    "API Gateway Latency ms",
    "API Gateway Rate Limit",
    "API Gateway Rate Remaining",
    "API Gateway Threat Signal",
    "WAF Action",
    "Chaos Injected",
    "Chaos Scenario",
    "Chaos TTL Seconds",
    "Chaos Target",
)

OCTO_APM_WORKSHOP_FIELD_DISPLAY_NAMES = (
    "Service Name",
    "Service Namespace",
    "Severity Level",
    "Trace ID",
    "Span ID",
    "Parent Span ID",
    "Span Name",
    "Span Attributes",
    "Span Kind",
    "APM Domain",
    "Request ID",
    "Workflow ID",
    "Workflow Step",
    "Run ID",
    "Response Code",
    "Metric Name",
    "Metric Value",
    "Metric Unit",
    "DB Target",
    "DB Statement",
    "DB Elapsed ms",
    "DB Connection Name",
    "Error Type",
    "Java APM Path",
    "Java APM Latency ms",
    "Java APM Error Type",
    "Attack ID",
    "Attack Stage",
    "Security Severity",
    "MITRE Tactic",
    "MITRE Technique ID",
    "Destination IP",
    "Destination Port",
    "OSQuery Query",
    "OSQuery Finding",
    "OSQuery SQL",
    "Instance OCID",
    "Host Name",
    "Host Role",
    "Compromised VM",
    "Process Command Line",
    "Order ID",
    "Source Order ID",
    "Payment Gateway Request ID",
    "Payment Provider",
    "Payment Status",
    "Payment Network",
    "Payment Wallet Token Hash",
    "Payment Risk Score",
    "Payment Card Last4",
    "Gateway",
    "Provider",
    "Version",
    "Step Id",
    "Process Phase",
    "Event Status",
    "Elapsed Time (Gateway)",
    "Request Type",
    "Authorization Scheme",
    "Method",
    "ORDER_AMOUNT",
    "BillingCurrency",
    "Gateway ID",
    "Transaction ID",
    "Result",
    "Security Result",
    "Program",
    "Flow Code",
    "Flow",
    "Downstream Component",
    "Payment Interception",
    "Payment Redirect",
    "Payment Redirect URL",
    "HTTP Redirect Location",
    "API Gateway Request ID",
    "API Gateway Action",
    "API Gateway Policy Decision",
    "API Gateway Route",
    "API Gateway Threat Signal",
)
APP_EXAMPLE = {
    "timestamp": "2026-03-18T09:07:04.446Z",
    "serviceName": "enterprise-crm-portal",
    "service.name": "enterprise-crm-portal",
    "service.namespace": "octo",
    "service.version": "1.1.0",
    "service.instance.id": "crm-portal-01",
    "deployment.environment": "production",
    "app.name": "enterprise-crm-portal",
    "app.brand": "OCTO CRM APM",
    "app.runtime": "python",
    "app.service": "enterprise-crm-portal",
    "traceId": "trace_demo_cross_service_001",
    "trace_id": "trace_demo_cross_service_001",
    "span_id": "span_demo_root_001",
    "oracleApmTraceId": "trace_demo_cross_service_001",
    "oracleApmSpanId": "span_demo_root_001",
    "traceparent": "00-trace_demo_cross_service_001-span_demo_root_001-01",
    "httpMethod": "GET",
    "http.method": "GET",
    "http.request.method": "GET",
    "http.request.method": "GET",
    "requestUrl": "/crm/orders/42",
    "uriPath": "/crm/orders/42",
    "http.url.path": "/crm/orders/42",
    "queryString": "",
    "statusCode": "200",
    "http.status_code": 200,
    "http.response.status_code": 200,
    "responseTimeMs": 842,
    "http.response_time_ms": 842,
    "clientAddress": "185.220.101.1",
    "http.client_ip": "185.220.101.1",
    "client.address": "185.220.101.1",
    "userAgent": "Mozilla/5.0 (compatible; demo-browser)",
    "user_agent.original": "Mozilla/5.0 (compatible; demo-browser)",
    "http.user_agent": "Mozilla/5.0 (compatible; demo-browser)",
    "user": "cersei",
    "sessionId": "sess_demo_001",
    "requestId": "req_demo_001",
    "request_id": "req_demo_001",
    "workflow_id": "crm-order-sync",
    "workflow_step": "order-detail",
    "correlation.id": "trace_demo_cross_service_001",
    "run_id": "run-octo-attack-lab-001",
    "contentType": "text/html",
    "referrer": "",
    "responseHeaders": "Content-Type: text/html; charset=utf-8",
    "spanName": "HTTP GET /crm/orders/:id",
    "spanAttributes": "document.cookie canvas.toDataURL webgl.getParameter",
    "spanId": "span_demo_root_001",
    "parentSpanId": "",
    "spanKind": "SERVER",
    "apmDomain": "octo-apm-demo",
    "metricName": "http.server.duration",
    "metricValue": "842",
    "metricUnit": "ms",
    "securityAttackType": "xss_reflected",
    "securityAttackSeverity": "high",
    "wafScore": "88",
    "dbTarget": "oracle_atp",
    "db.target": "oracle_atp",
    "db.statement": "select * from orders where id = :id",
    "db.elapsed_ms": 155,
    "db.connection_name": "octo_atp_tp",
    "db.ocid": "ocid1.autonomousdatabase.oc1..example",
    "errorType": "",
    "slowRequest": "false",
    "performance.slow_request": False,
    "java_apm.path": "/api/java-apm/payment/authorize",
    "java_apm.status_code": 200,
    "java_apm.latency_ms": 135,
    "java_apm.error_type": "",
    "security.attack.id": "attack-octo-demo-001",
    "security.attack.stage": "payment_redirect",
    "security.attack.type": "payment_redirect",
    "security.attack.payload": "redirect checkout payment flow",
    "security.attack.detected": True,
    "security.severity": "critical",
    "mitre.tactic": "Credential Access",
    "mitre.technique_id": "T1557",
    "mitre.technique": "Adversary-in-the-Middle",
    "attack.entry_point": "/shop/checkout/payment/redirect",
    "attack.lotl_binary": "nginx-rewrite",
    "source.ip": "203.0.113.77",
    "server.address": "octo-shop-vm-01",
    "destination.ip": "198.51.100.44",
    "destination.port": 443,
    "network.protocol.name": "https",
    "osquery.query": "suspicious-shell-history",
    "osquery.finding": "redirect rule simulation points payment flow to a suspicious host",
    "osquery.sql": "SELECT pid, name, path, cmdline FROM processes;",
    "osquery.result_count": 1,
    "cloud.instance.id": "ocid1.instance.oc1.iad.demoattackshop01",
    "host.name": "octo-shop-vm-01",
    "host.role": "shop-frontend",
    "vm.compromised": True,
    "process.name": "nginx",
    "process.command_line": "nginx -s reload",
    "file.path": "/etc/nginx/conf.d/payment_redirect.conf",
    "payment.provider": "simulated",
    "payment.status": "redirected",
    "payment.risk_score": 97,
    "payment.card_brand": "visa",
    "payment.card_last4": "4242",
    "payment.interception.detected": True,
    "payment.redirect.detected": True,
    "payment.redirect.url": "https://pay-update.example.test/checkout/session",
    "http.redirect.location": "https://pay-update.example.test/checkout/session",
    "network.bytes_out": 4812,
    "wafAction": "DETECT",
    "waf.action": "DETECT",
    "chaos.injected": "false",
    "chaos.scenario": "",
    "chaos.ttl_seconds": 0,
    "chaos.target": "",
    "ordersSyncCreated": 0,
    "ordersSyncUpdated": 0,
    "ordersSyncFailed": 0,
    "ordersSyncSource": "",
    "level": "INFO",
    "severity": "INFO",
    "hostname": "crm-portal-01",
    "business_id": "order-42",
    "user_id_hash": "usr_demo_hash_001",
    "oci.api_gateway.name": "octo-public-api-gateway",
    "oci.api_gateway.scope": "public",
    "oci.api_gateway.deployment_id": "ocid1.apigatewaydeployment.oc1.iad.demo",
    "oci.api_gateway.route": "/api/shop/attack/simulate",
    "oci.api_gateway.route_id": "public-attack-simulate",
    "oci.api_gateway.route_family": "shop_attack",
    "oci.api_gateway.request_id": "gw-req-demo-001",
    "oci.api_gateway.action": "allow",
    "oci.api_gateway.policy.decision": "suspicious_burst_observed",
    "oci.api_gateway.latency_ms": 34,
    "oci.api_gateway.rate_limit.limit": 120,
    "oci.api_gateway.rate_limit.remaining": 87,
    "oci.api_gateway.threat_signal": "attack_lab_probe",
    "message": "Browser telemetry recorded suspicious request",
}

APP_SOURCE_INTERNAL = "socApplicationSource"
APP_SOURCE_DISPLAY = "SOC Application Logs"
APP_SOURCE_DESC = (
    "Application and browser telemetry from OCI-DEMO services in JSON format. "
    "Used by the Application 360 and browser attack dashboards."
)
