"""Static log-source/parser/field definitions (custom field catalog + data-type overrides + parser-field reservations).

Auto-extracted from setup_log_sources.py (behavior-preserving). Pure data — no
logic, no OCI calls.
"""

CUSTOM_FIELDS = [
    "Command Line",
    "Process Name",
    "Parent Process Name",
    "Parent Command Line",
    "Original File Name",
    "Event ID",
    "Host Name",
    "Problem Name",
    "Problem ID",
    "Risk Level",
    "Risk Score",
    "Lifecycle State",
    "Detector Rule ID",
    "Resource Type",
    "Resource ID",
    "Resource Name",
    "Region",
    "Utc Time",
    "Process Guid",
    "Parent Process Guid",
    "Parent Process ID",
    "Current Directory",
    "Company",
    "Product",
    "Description",
    "Logon ID",
    "Logon Guid",
    "Integrity Level",
    "Facility",
    "Severity Level",
    "Process ID",
    # Additional fields for multicloudoperations widget compatibility
    "Host Name (Server)",
    "Source Address",
    "Logon Type",
    "Endpoint OS",
    "Source Process",
    "Target Process",
    "Destination Hostname",
    "Destination IP",
    "Destination Port",
    "Query Name",
    "Query Results",
    "Pipe Name",
    "Target Filename",
    "Target Object",
    "Granted Access",
    "Source IP",
    "Source Port",
    "Auth Method",
    "Session Type",
    "Service Name",
    "Process",
    "Service",
    "Severity",
    "Original Log Content",
    # Windows Security advanced auth fields (Kerberos / privilege / explicit-creds events)
    # Required by detections: golden_ticket_*, kerberoasting_*, pass-the-ticket_*,
    # privilege_escalation_sensitive_privileges_assigned_to_non-admin, dcsync_*
    "Subject User Name",
    "Target User Name",
    "Target Domain Name",
    "Ticket Encryption Type",
    "Ticket Options",
    "Privilege List",
    "Target Server Name",
    "Service Information",
    "Object Server",
    "Object Type",
    "Properties",
    "Object Name",
    "Access Mask",
    "Failure Reason",
    "Sub Status",
    "Task Name",
    "Share Name",
    "Relative Target Name",
    "Service File Name",
    "Script Block Text",
    "Host Application",
    "Threat ID",
    "Detection Source",
    # Sysmon Network / MITRE fields
    "Account Name",
    "RuleName",
    "Technique Name",
    "Technique ID",
    "Protocol",
    "Initiated",
    "Event Channel",
    # Sysmon process / Cloud Guard fields
    "Hashes",
    "Detector ID",
    # WAF / Web Application fields
    "Action",
    "HTTP Method",
    "HTTP Request Method",
    "Request URL",
    "URI Path",
    "Query String",
    "Client IP",
    "Country Code",
    "User Agent",
    "Response Code",
    "Rule Type",
    "Rule Key",
    "Rule Action",
    "WAF Action",
    "Request Body",
    "Content Type",
    "Referrer",
    "Request Headers",
    "WAF Policy",
    "Threat Feeds",
    "Fingerprint",
    "Response Headers",
    "WAF Score",
    # Load Balancer fields
    "Backend Address",
    "Backend Status Code",
    "Bytes Received",
    "Bytes Sent",
    "Request Processing Time",
    "Load Balancer Name",
    "Listener Name",
    "Backend Name",
    # Web Application fields
    "Application Name",
    "Attack Type",
    "Attack Payload",
    "Vulnerability ID",
    "Session ID",
    "OWASP Category",
    "Request ID",
    "Trace ID",
    "Trace Parent",
    "Span Name",
    "Span Attributes",
    "Span ID",
    "Parent Span ID",
    "Span Kind",
    "APM Domain",
    "Service Namespace",
    "Service Version",
    "Service Instance ID",
    "Deployment Environment",
    "App Name",
    "App Brand",
    "App Runtime",
    "App Service",
    "Workflow ID",
    "Workflow Step",
    "Correlation ID",
    "Run ID",
    "Metric Name",
    "Metric Value",
    "Metric Unit",
    "DB Target",
    "DB Statement",
    "DB Elapsed ms",
    "DB Connection Name",
    "DB OCID",
    "Error Type",
    "Slow Request",
    "URL Path",
    "HTTP Status Code",
    "Java APM Path",
    "Java APM Status Code",
    "Java APM Latency ms",
    "Java APM Error Type",
    "Attack ID",
    "Attack Stage",
    "Attack Entry Point",
    "LOTL Binary",
    "Security Severity",
    "MITRE Tactic",
    "MITRE Technique ID",
    "MITRE Technique",
    "Server Address",
    "Network Protocol",
    "OSQuery Query",
    "OSQuery Finding",
    "OSQuery SQL",
    "OSQuery Result Count",
    "Pack Name",
    "Pack Query ID",
    "Pack Query Name",
    "Finding ID",
    "Finding Name",
    "Finding Status",
    "Finding Severity",
    "Instance Security Problem ID",
    "Instance Security Rule ID",
    "Instance OCID",
    "Host Role",
    "Compromised VM",
    "Process Name",
    "Process Command Line",
    "File Path",
    "Payment Provider",
    "Payment Status",
    "Payment Gateway Request ID",
    "Payment Network",
    "Payment Wallet Token Hash",
    "Payment Risk Score",
    "Payment Card Last4",
    "Order ID",
    "Source Order ID",
    "Gateway",
    "Provider",
    "Version",
    "Step Id",
    "Process Phase",
    "Event Status",
    "Elapsed Time (Gateway)",
    "Request Type",
    "Authorization Scheme",
    "Method",
    "ORDER_AMOUNT",
    "BillingCurrency",
    "Gateway ID",
    "Transaction ID",
    "Result",
    "Security Result",
    "Program",
    "Flow Code",
    "Flow",
    "Downstream Component",
    "Payment Interception",
    "Payment Redirect",
    "Payment Redirect URL",
    "HTTP Redirect Location",
    "Network Bytes Out",
    "User ID (hashed)",
    "Business ID",
    "API Gateway Name",
    "API Gateway Scope",
    "API Gateway Deployment ID",
    "API Gateway Route",
    "API Gateway Route ID",
    "API Gateway Route Family",
    "API Gateway Request ID",
    "API Gateway Action",
    "API Gateway Policy Decision",
    "API Gateway Latency ms",
    "API Gateway Rate Limit",
    "API Gateway Rate Remaining",
    "API Gateway Threat Signal",
    "Chaos Injected",
    "Chaos Scenario",
    "Chaos TTL Seconds",
    "Chaos Target",
    "Orders Sync Created",
    "Orders Sync Updated",
    "Orders Sync Failed",
    "Orders Sync Source",
    # Multicloud Health / Geographic fields
    "Cloud Provider",
    "Region Display",
    "Country",
    "Latitude",
    "Longitude",
    "Instance ID",
    "Instance Role",
    "Tier",
    "Operating System",
    "Instance Type",
    "Status",
    "Status Code",
    "CPU Percent",
    "Memory Percent",
    "Disk Percent",
    "Network In Mbps",
    "Network Out Mbps",
    "Uptime Hours",
    "Open Connections",
    "Response Time Ms",
    "Heartbeat Sequence",
    "IP Address",
    # OCI network telemetry fields
    "Flow ID",
    "Packets",
    "Network Action",
    "Log Type",
    "Firewall Rule",
    "Threat Name",
    "Threat Category",
    "Direction",
    # GenAI / LLM gateway fields (MITRE ATLAS coverage — SOC GenAI Gateway Logs)
    "GenAI Provider",
    "GenAI Model",
    "GenAI Endpoint",
    "GenAI Operation",
    "GenAI Prompt",
    "GenAI Completion",
    "GenAI Prompt Tokens",
    "GenAI Completion Tokens",
    "GenAI Total Tokens",
    "GenAI Latency ms",
    "GenAI Finish Reason",
    "GenAI Request ID",
    "GenAI Identity",
    "API Key ID",
    "Guardrail Action",
    "Guardrail Category",
    "Gateway Decision",
    "Prompt Risk Score",
    "Injection Detected",
    "Jailbreak Detected",
    "Data Leak Detected",
    "Model Source",
    "Model Version",
    "Model Hash",
    "Model Signature Valid",
    "ATLAS Tactic",
    "ATLAS Technique ID",
]


FIELD_DATA_TYPE_OVERRIDES = {
    "HTTP Status Code": "LONG",
    "Java APM Status Code": "LONG",
    "Java APM Latency ms": "LONG",
    "DB Elapsed ms": "LONG",
    "Destination Port": "LONG",
    "OSQuery Result Count": "LONG",
    "Payment Risk Score": "LONG",
    "Elapsed Time (Gateway)": "FLOAT",
    "ORDER_AMOUNT": "FLOAT",
    "Network Bytes Out": "LONG",
    "API Gateway Latency ms": "LONG",
    "API Gateway Rate Limit": "LONG",
    "API Gateway Rate Remaining": "LONG",
    "Chaos TTL Seconds": "LONG",
    "GenAI Prompt Tokens": "LONG",
    "GenAI Completion Tokens": "LONG",
    "GenAI Total Tokens": "LONG",
    "GenAI Latency ms": "LONG",
    "Prompt Risk Score": "LONG",
}


# Existing OCI fields with different display names can be useful, but parser
# mappings cannot safely substitute them unless saved searches are also updated
# to the reused display name. Keep these as audit-only rewrite candidates.
FIELD_REWRITE_REUSE_CANDIDATES = {
    "Service Name": ("Service",),
    "Severity Level": ("Severity",),
    "Host Name": ("Host Name (Server)",),
    "HTTP Request Method": ("HTTP Method",),
    "Response Code": ("HTTP Status Code", "Status Code"),
    "URL Path": ("URI Path",),
    "Source IP": ("Source Address",),
    "Process Command Line": ("Command Line",),
}

RESERVED_PARSER_FIELD_DISPLAY_NAMES = {
    "Original Log Content",
}


# ─── Linux Syslog Parser ────────────────────────────────────────
