name: GCP Terraform

on:
    pull_request:
        branches: [main]
        paths:
            - "gcp/**"
            - "!gcp/**/ansible/**"
    push:
        branches: [main]
        paths:
            - "gcp/**"
            - "!gcp/**/ansible/**"
    workflow_dispatch:

jobs:
    terraform:
        if: github.event_name != 'push' || github.event.before != '0000000000000000000000000000000000000000'
        uses: __CUSTOMER_ORG__/platform-ci/.github/workflows/terraform-shared.yaml@__PLATFORM_CI_REF__
        secrets: inherit
        with:
            mode: ${{ github.event_name == 'push' && 'apply' || 'pr' }}
            cloud: gcp
            orchestrator_repo: oci-clickops/clickops-orchestrator-gcp
            orchestrator_ref: c434e0697a3ca4daa8f8c7903afd4c6c7be287f9
            bucket_name: gitops-state-bucket
