apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: reference-app
    app.kubernetes.io/part-of: reference-app
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: reference-app
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 80
      targetPort: http
