apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      reconcile.fluxcd.io/watch: Enabled

resources:
  - ../../base

configMapGenerator:
  - name: ${component}-values-${environment}
    files:
      - values.yaml=./values.yml

secretGenerator:
  - name: ${component}-values-env-${environment}
    files:
      - values.yaml=./secrets.yml

generatorOptions:
  disableNameSuffixHash: true
