###############################################################################
# Copyright (c) 2022, 2023, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License
# (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl.
###############################################################################
#
# Author: Fabrizio Zarri
#
################################################################################

title: "Automate loading Data Safe DB Audit log data to OCI logging using a serverless application"
stackDescription: "Automate loading Data Safe DB Audit log data to OCI logging using a serverless application."
schemaVersion: 1.1.0
version: "20230622"
locale: "en"

variableGroups:
- title: General Configuration
  visible: false
  variables:
  - tenancy_ocid
  - region
  - release
  - ocir_repo_name
  - compartment_ocid
  - dashboard_files


- title: Collection Details (function, network, and object storage)
  visible: true  
  variables:
  - ocir_user_name
  - ocir_user_password
  - deployment_name
  - create_network
  - show_advanced_collection


- title: Select	Network Subnet
  visible:
      not:
        - create_network
  variables:
  - subnet_ocid

- title: Network Setup
  visible:
      and:
        - create_network
        - show_advanced_collection
  variables:
  - vcn_cidr
  - fnsubnet_cidr

- title: Optional Collection Details
  visible:
      and:
        - show_advanced_collection
  variables:
  - tracker-bucket
  - test
  - setup_policies


variables:
  
  setup_policies:
    type: boolean
    title: "Setup Policies for Function?"
    description: "Uncheck only if policies has already been set for functions in this compartment."
    visible: true
    default: true

  create_network:
    type: boolean
    title: "Create Network"
    description: "Uncheck only if you already have a private subnet with security policies."
    visible: true
    default: true

  compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    visibile: true
    title: "Compartment"
    description: "Choose compartment where you want to create the solution resources."

  region:
    type: oci:identity:region:name
    required: true
    visibile: true
    title: "Region"
    description: "Choose region where you want to deploy the resources defined by this stack."

  subnet_ocid:
    type: oci:core:subnet:id
    required:
         not:
          create_network
    visibile:
         not:
          create_network
    title: "Subnet"
    description: "Select an existing subnet for creating resources."
    dependsOn:
      compartmentId: ${compartment_ocid}

  ocir_user_name:
    type: string
    required: true
    visibile: true
    title: "OCIR username"
    description: "Oracle Cloud Infrastructure Registry username (your OCI username)." 

  ocir_user_password:
    type: password
    required: true
    visibile: true
    title: "OCIR user password"
    description: "Oracle Cloud Infrastructure Registry user password (your OCI user authtoken)." 
  
  deployment_name:
    type: string
    required: true
    visibile: true
    title: "Deployement Mode"
    description: "Function Deployment Mod (prod, test, dev)"
    pattern: "^[a-z]+$" 

  # Optional Configuration

  vcn_cidr:
    type: string
    required: false
    default: "10.0.0.0/16"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "VCN CIDR"
    description: "Choose VCN's CIDR block where Fn App will be deployed."

  subnet_cidr:
    type: string
    required: false
    default: "10.0.2.0/24"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "Subnet CIDR"
    description: "Choose Private Subnet's CIDR where Fn App will be deployed."  

outputs: