apiVersion: v1
kind: LimitRange
metadata:
  name: defaults
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 10m
        memory: 16Mi
      default:
        cpu: 100m
        memory: 64Mi
